import type {
  BillingTransaction,
  ClaimsNotices,
  ClearVanityNameserverSetDefaultRes,
  Contact,
  ContactAttestRes,
  ContactAttributeLink,
  ContactAttributeSet,
  ContactVerification,
  ContextList,
  Conversation,
  ConversationList,
  CreateJobBatch,
  DnsChanges,
  DnsZone,
  DnsZoneSummary,
  DnsZoneVanitySetUpdateRes,
  Domain,
  DomainAvailabilityList,
  DomainCheck,
  DomainDnssecData,
  DomainForward,
  DomainForwardBrowserStats,
  DomainForwardGeoStats,
  DomainForwardMetrics,
  DomainForwardMetricsTimeSeries,
  DomainForwardPlatformStats,
  DomainForwardReferrerStats,
  DomainForwardSet,
  DomainForwardStatusCodeStats,
  DomainForwardUserAgentStats,
  DomainForwardVisitsByKey,
  DomainForwardZone,
  DomainRenew,
  DomainRestore,
  DomainSearch,
  DomainSummary,
  DomainTransit,
  DomainWithdraw,
  EmailForward,
  EmailForwardAlias,
  EmailForwardMetrics,
  EmailForwardZone,
  EventResponse,
  GetPrices,
  HTTPValidationError,
  Host,
  IpRestriction,
  Job,
  JobBatchRetry,
  JobBatchStatus,
  ListVanityNameserverSetsRes,
  ListZonesReferencingSetRes,
  MemoryFact,
  MemoryFactList,
  Message,
  MessageList,
  NorIdDeclaration,
  ObjectTagChanges2,
  Organization,
  OrganizationAttribute2,
  OrganizationCredential,
  OrganizationWithBillingData,
  PageResponse_EmailForwardLog,
  PageResponse_Job,
  PageResponse_JobBatchMetadata,
  PageResponse_ObjectLog,
  PageResponse_Parking,
  PageResponse_RequestHistory,
  Pagination_BillingTransaction,
  Pagination_Contact,
  Pagination_ContactAttributeSet,
  Pagination_DnsZone,
  Pagination_Domain,
  Pagination_DomainForward,
  Pagination_DomainForwardZone,
  Pagination_EmailForward,
  Pagination_EmailForwardZone,
  Pagination_Event,
  Pagination_Invoice,
  Pagination_Organization,
  Pagination_Tag,
  Pagination_UserPublicWithRole,
  ParkingMetrics,
  ParkingSignup,
  ParkingSignupStatus,
  ParkingTotalMetrics,
  Problem,
  PublicPermissionSet,
  PublicReportListRes,
  PublicReportRes,
  PublicRoleAssignment,
  PublicRoleDefinition,
  RequestAuthcode,
  RequestAuthcode2,
  RequestAuthcode3,
  SetVanityNameserverSetDefaultRes,
  Tag,
  TldResponseShort,
  TldSpecification,
  UserProfile,
  UserPublic,
  UserPublicWithAttributes,
  VanityNameserverSetSummaryDTO,
  VanityNsCheckRes,
} from './schemas';

export type DELETE_AiConciergeConversationsByConversationId_Response = DELETE_AiConciergeConversationsByConversationId_Response_401 | DELETE_AiConciergeConversationsByConversationId_Response_404 | DELETE_AiConciergeConversationsByConversationId_Response_422 | DELETE_AiConciergeConversationsByConversationId_Response_502;

export type DELETE_AiConciergeConversationsByConversationId_Response_401 = Problem;
export type DELETE_AiConciergeConversationsByConversationId_Response_404 = Problem;
export type DELETE_AiConciergeConversationsByConversationId_Response_422 = HTTPValidationError;
export type DELETE_AiConciergeConversationsByConversationId_Response_502 = Problem;

export type DELETE_AiConciergeMemoryFactsByFactId_Response = DELETE_AiConciergeMemoryFactsByFactId_Response_401 | DELETE_AiConciergeMemoryFactsByFactId_Response_404 | DELETE_AiConciergeMemoryFactsByFactId_Response_422 | DELETE_AiConciergeMemoryFactsByFactId_Response_502;

export type DELETE_AiConciergeMemoryFactsByFactId_Response_401 = Problem;
export type DELETE_AiConciergeMemoryFactsByFactId_Response_404 = Problem;
export type DELETE_AiConciergeMemoryFactsByFactId_Response_422 = HTTPValidationError;
export type DELETE_AiConciergeMemoryFactsByFactId_Response_502 = Problem;

export type DELETE_ContactsAttributeSetsByContactAttributeSetId_Response = DELETE_ContactsAttributeSetsByContactAttributeSetId_Response_404 | DELETE_ContactsAttributeSetsByContactAttributeSetId_Response_422;

export type DELETE_ContactsAttributeSetsByContactAttributeSetId_Response_404 = Problem;
export type DELETE_ContactsAttributeSetsByContactAttributeSetId_Response_422 = HTTPValidationError;

export type DELETE_ContactsByContactId_Response = DELETE_ContactsByContactId_Response_404 | DELETE_ContactsByContactId_Response_409 | DELETE_ContactsByContactId_Response_422;

export type DELETE_ContactsByContactId_Response_404 = Problem;
export type DELETE_ContactsByContactId_Response_409 = Problem;
export type DELETE_ContactsByContactId_Response_422 = HTTPValidationError;

export type DELETE_ContactsByContactIdVerification_Response = DELETE_ContactsByContactIdVerification_Response_401 | DELETE_ContactsByContactIdVerification_Response_404 | DELETE_ContactsByContactIdVerification_Response_422;

export type DELETE_ContactsByContactIdVerification_Response_401 = Problem;
export type DELETE_ContactsByContactIdVerification_Response_404 = Problem;
export type DELETE_ContactsByContactIdVerification_Response_422 = HTTPValidationError;

export type DELETE_DnsByZoneName_Response = DELETE_DnsByZoneName_Response_422;

export type DELETE_DnsByZoneName_Response_422 = HTTPValidationError;

export type DELETE_DomainForwardsByHostname_Response = DELETE_DomainForwardsByHostname_Response_401 | DELETE_DomainForwardsByHostname_Response_403 | DELETE_DomainForwardsByHostname_Response_404 | DELETE_DomainForwardsByHostname_Response_422;

export type DELETE_DomainForwardsByHostname_Response_401 = Problem;
export type DELETE_DomainForwardsByHostname_Response_403 = Problem;
export type DELETE_DomainForwardsByHostname_Response_404 = Problem;
export type DELETE_DomainForwardsByHostname_Response_422 = HTTPValidationError;

export type DELETE_DomainForwardsByHostnameByProtocol_Response = DELETE_DomainForwardsByHostnameByProtocol_Response_401 | DELETE_DomainForwardsByHostnameByProtocol_Response_403 | DELETE_DomainForwardsByHostnameByProtocol_Response_404 | DELETE_DomainForwardsByHostnameByProtocol_Response_422;

export type DELETE_DomainForwardsByHostnameByProtocol_Response_401 = Problem;
export type DELETE_DomainForwardsByHostnameByProtocol_Response_403 = Problem;
export type DELETE_DomainForwardsByHostnameByProtocol_Response_404 = Problem;
export type DELETE_DomainForwardsByHostnameByProtocol_Response_422 = HTTPValidationError;

export type DELETE_DomainsByDomainReference_Response = DELETE_DomainsByDomainReference_Response_404 | DELETE_DomainsByDomainReference_Response_409 | DELETE_DomainsByDomainReference_Response_422;

export type DELETE_DomainsByDomainReference_Response_404 = Problem;
export type DELETE_DomainsByDomainReference_Response_409 = Problem;
export type DELETE_DomainsByDomainReference_Response_422 = HTTPValidationError;

export type DELETE_DomainsByDomainReferenceDnssec_Response = DELETE_DomainsByDomainReferenceDnssec_Response_404 | DELETE_DomainsByDomainReferenceDnssec_Response_422;

export type DELETE_DomainsByDomainReferenceDnssec_Response_404 = Problem;
export type DELETE_DomainsByDomainReferenceDnssec_Response_422 = HTTPValidationError;

export type DELETE_DomainsByDomainReferenceTransfer_Response = DELETE_DomainsByDomainReferenceTransfer_Response_404 | DELETE_DomainsByDomainReferenceTransfer_Response_409 | DELETE_DomainsByDomainReferenceTransfer_Response_422;

export type DELETE_DomainsByDomainReferenceTransfer_Response_404 = Problem;
export type DELETE_DomainsByDomainReferenceTransfer_Response_409 = Problem;
export type DELETE_DomainsByDomainReferenceTransfer_Response_422 = HTTPValidationError;

export type DELETE_EmailForwardsByEmailForwardId_Response = DELETE_EmailForwardsByEmailForwardId_Response_401 | DELETE_EmailForwardsByEmailForwardId_Response_403 | DELETE_EmailForwardsByEmailForwardId_Response_422;

export type DELETE_EmailForwardsByEmailForwardId_Response_401 = Problem;
export type DELETE_EmailForwardsByEmailForwardId_Response_403 = Problem;
export type DELETE_EmailForwardsByEmailForwardId_Response_422 = HTTPValidationError;

export type DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response = DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_401 | DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_403 | DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_404 | DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_422;

export type DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_401 = Problem;
export type DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_403 = Problem;
export type DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_404 = Problem;
export type DELETE_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_422 = HTTPValidationError;

export type DELETE_HostsByHostReference_Response = DELETE_HostsByHostReference_Response_401 | DELETE_HostsByHostReference_Response_403 | DELETE_HostsByHostReference_Response_404 | DELETE_HostsByHostReference_Response_409 | DELETE_HostsByHostReference_Response_422;

export type DELETE_HostsByHostReference_Response_401 = Problem;
export type DELETE_HostsByHostReference_Response_403 = Problem;
export type DELETE_HostsByHostReference_Response_404 = Problem;
export type DELETE_HostsByHostReference_Response_409 = Problem;
export type DELETE_HostsByHostReference_Response_422 = HTTPValidationError;

export type DELETE_JobByJobId_Response = DELETE_JobByJobId_Response_404 | DELETE_JobByJobId_Response_422;

export type DELETE_JobByJobId_Response_404 = Problem;
export type DELETE_JobByJobId_Response_422 = HTTPValidationError;

export type DELETE_JobsByBatchId_Response = DELETE_JobsByBatchId_Response_404 | DELETE_JobsByBatchId_Response_422;

export type DELETE_JobsByBatchId_Response_404 = Problem;
export type DELETE_JobsByBatchId_Response_422 = HTTPValidationError;

export type DELETE_OrganizationsByOrganizationId_Response = DELETE_OrganizationsByOrganizationId_Response_401 | DELETE_OrganizationsByOrganizationId_Response_403 | DELETE_OrganizationsByOrganizationId_Response_422;

export type DELETE_OrganizationsByOrganizationId_Response_401 = Problem;
export type DELETE_OrganizationsByOrganizationId_Response_403 = Problem;
export type DELETE_OrganizationsByOrganizationId_Response_422 = HTTPValidationError;

export type DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response = DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response_401 | DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response_403 | DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response_422;

export type DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response_401 = Problem;
export type DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response_403 = Problem;
export type DELETE_OrganizationsIpRestrictionsByIpRestrictionId_Response_422 = HTTPValidationError;

export type DELETE_OrganizationsRolesByLabel_Response = DELETE_OrganizationsRolesByLabel_Response_401 | DELETE_OrganizationsRolesByLabel_Response_403 | DELETE_OrganizationsRolesByLabel_Response_404 | DELETE_OrganizationsRolesByLabel_Response_409 | DELETE_OrganizationsRolesByLabel_Response_422;

export type DELETE_OrganizationsRolesByLabel_Response_401 = Problem;
export type DELETE_OrganizationsRolesByLabel_Response_403 = Problem;
export type DELETE_OrganizationsRolesByLabel_Response_404 = Problem;
export type DELETE_OrganizationsRolesByLabel_Response_409 = Problem;
export type DELETE_OrganizationsRolesByLabel_Response_422 = HTTPValidationError;

export type DELETE_TagsByTagId_Response = DELETE_TagsByTagId_Response_401 | DELETE_TagsByTagId_Response_404 | DELETE_TagsByTagId_Response_422;

export type DELETE_TagsByTagId_Response_401 = Problem;
export type DELETE_TagsByTagId_Response_404 = Problem;
export type DELETE_TagsByTagId_Response_422 = HTTPValidationError;

export type DELETE_UsersByUserId_Response = DELETE_UsersByUserId_Response_403 | DELETE_UsersByUserId_Response_422;

export type DELETE_UsersByUserId_Response_403 = Problem;
export type DELETE_UsersByUserId_Response_422 = HTTPValidationError;

export type DELETE_VanityNameserverSetsBySetId_Response = DELETE_VanityNameserverSetsBySetId_Response_422;

export type DELETE_VanityNameserverSetsBySetId_Response_422 = HTTPValidationError;

export type DELETE_VanityNameserverSetsDefault_Response = DELETE_VanityNameserverSetsDefault_Response_200 | DELETE_VanityNameserverSetsDefault_Response_422;

export type DELETE_VanityNameserverSetsDefault_Response_200 = ClearVanityNameserverSetDefaultRes;
export type DELETE_VanityNameserverSetsDefault_Response_422 = HTTPValidationError;

export type GET_AiConciergeContextsByContextId_Response = GET_AiConciergeContextsByContextId_Response_401 | GET_AiConciergeContextsByContextId_Response_404 | GET_AiConciergeContextsByContextId_Response_422 | GET_AiConciergeContextsByContextId_Response_502;

export type GET_AiConciergeContextsByContextId_Response_401 = Problem;
export type GET_AiConciergeContextsByContextId_Response_404 = Problem;
export type GET_AiConciergeContextsByContextId_Response_422 = HTTPValidationError;
export type GET_AiConciergeContextsByContextId_Response_502 = Problem;

export type GET_AiConciergeConversations_Response = GET_AiConciergeConversations_Response_200 | GET_AiConciergeConversations_Response_401 | GET_AiConciergeConversations_Response_404 | GET_AiConciergeConversations_Response_422 | GET_AiConciergeConversations_Response_502;

export type GET_AiConciergeConversations_Response_200 = ConversationList;
export type GET_AiConciergeConversations_Response_401 = Problem;
export type GET_AiConciergeConversations_Response_404 = Problem;
export type GET_AiConciergeConversations_Response_422 = HTTPValidationError;
export type GET_AiConciergeConversations_Response_502 = Problem;

export type GET_AiConciergeConversationsByConversationId_Response = GET_AiConciergeConversationsByConversationId_Response_200 | GET_AiConciergeConversationsByConversationId_Response_401 | GET_AiConciergeConversationsByConversationId_Response_404 | GET_AiConciergeConversationsByConversationId_Response_422 | GET_AiConciergeConversationsByConversationId_Response_502;

export type GET_AiConciergeConversationsByConversationId_Response_200 = Conversation;
export type GET_AiConciergeConversationsByConversationId_Response_401 = Problem;
export type GET_AiConciergeConversationsByConversationId_Response_404 = Problem;
export type GET_AiConciergeConversationsByConversationId_Response_422 = HTTPValidationError;
export type GET_AiConciergeConversationsByConversationId_Response_502 = Problem;

export type GET_AiConciergeConversationsByConversationIdContexts_Response = GET_AiConciergeConversationsByConversationIdContexts_Response_200 | GET_AiConciergeConversationsByConversationIdContexts_Response_401 | GET_AiConciergeConversationsByConversationIdContexts_Response_404 | GET_AiConciergeConversationsByConversationIdContexts_Response_422 | GET_AiConciergeConversationsByConversationIdContexts_Response_502;

export type GET_AiConciergeConversationsByConversationIdContexts_Response_200 = ContextList;
export type GET_AiConciergeConversationsByConversationIdContexts_Response_401 = Problem;
export type GET_AiConciergeConversationsByConversationIdContexts_Response_404 = Problem;
export type GET_AiConciergeConversationsByConversationIdContexts_Response_422 = HTTPValidationError;
export type GET_AiConciergeConversationsByConversationIdContexts_Response_502 = Problem;

export type GET_AiConciergeConversationsByConversationIdMessages_Response = GET_AiConciergeConversationsByConversationIdMessages_Response_200 | GET_AiConciergeConversationsByConversationIdMessages_Response_401 | GET_AiConciergeConversationsByConversationIdMessages_Response_404 | GET_AiConciergeConversationsByConversationIdMessages_Response_422 | GET_AiConciergeConversationsByConversationIdMessages_Response_502;

export type GET_AiConciergeConversationsByConversationIdMessages_Response_200 = MessageList;
export type GET_AiConciergeConversationsByConversationIdMessages_Response_401 = Problem;
export type GET_AiConciergeConversationsByConversationIdMessages_Response_404 = Problem;
export type GET_AiConciergeConversationsByConversationIdMessages_Response_422 = HTTPValidationError;
export type GET_AiConciergeConversationsByConversationIdMessages_Response_502 = Problem;

export type GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response = GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_200 | GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_401 | GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_404 | GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_422 | GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_502;

export type GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_200 = Message;
export type GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_401 = Problem;
export type GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_404 = Problem;
export type GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_422 = HTTPValidationError;
export type GET_AiConciergeConversationsByConversationIdMessagesByMessageId_Response_502 = Problem;

export type GET_AiConciergeMemoryFacts_Response = GET_AiConciergeMemoryFacts_Response_200 | GET_AiConciergeMemoryFacts_Response_401 | GET_AiConciergeMemoryFacts_Response_404 | GET_AiConciergeMemoryFacts_Response_422 | GET_AiConciergeMemoryFacts_Response_502;

export type GET_AiConciergeMemoryFacts_Response_200 = MemoryFactList;
export type GET_AiConciergeMemoryFacts_Response_401 = Problem;
export type GET_AiConciergeMemoryFacts_Response_404 = Problem;
export type GET_AiConciergeMemoryFacts_Response_422 = HTTPValidationError;
export type GET_AiConciergeMemoryFacts_Response_502 = Problem;

export type GET_ArchiveEmailForwardLogsAliasesByEmailForwardAliasId_Response = GET_ArchiveEmailForwardLogsAliasesByEmailForwardAliasId_Response_200 | GET_ArchiveEmailForwardLogsAliasesByEmailForwardAliasId_Response_422;

export type GET_ArchiveEmailForwardLogsAliasesByEmailForwardAliasId_Response_200 = PageResponse_EmailForwardLog;
export type GET_ArchiveEmailForwardLogsAliasesByEmailForwardAliasId_Response_422 = HTTPValidationError;

export type GET_ArchiveEmailForwardLogsByEmailForwardId_Response = GET_ArchiveEmailForwardLogsByEmailForwardId_Response_200 | GET_ArchiveEmailForwardLogsByEmailForwardId_Response_422;

export type GET_ArchiveEmailForwardLogsByEmailForwardId_Response_200 = PageResponse_EmailForwardLog;
export type GET_ArchiveEmailForwardLogsByEmailForwardId_Response_422 = HTTPValidationError;

export type GET_ArchiveObjectLogs_Response = GET_ArchiveObjectLogs_Response_200 | GET_ArchiveObjectLogs_Response_422;

export type GET_ArchiveObjectLogs_Response_200 = PageResponse_ObjectLog;
export type GET_ArchiveObjectLogs_Response_422 = HTTPValidationError;

export type GET_ArchiveObjectLogsByObjectId_Response = GET_ArchiveObjectLogsByObjectId_Response_200 | GET_ArchiveObjectLogsByObjectId_Response_422;

export type GET_ArchiveObjectLogsByObjectId_Response_200 = PageResponse_ObjectLog;
export type GET_ArchiveObjectLogsByObjectId_Response_422 = HTTPValidationError;

export type GET_ArchiveRequestHistory_Response = GET_ArchiveRequestHistory_Response_200 | GET_ArchiveRequestHistory_Response_422;

export type GET_ArchiveRequestHistory_Response_200 = PageResponse_RequestHistory;
export type GET_ArchiveRequestHistory_Response_422 = HTTPValidationError;

export type GET_AuthClientCredentialsIntrospect_Response = GET_AuthClientCredentialsIntrospect_Response_200 | GET_AuthClientCredentialsIntrospect_Response_401 | GET_AuthClientCredentialsIntrospect_Response_422;

export type GET_AuthClientCredentialsIntrospect_Response_200 = OrganizationCredential;
export type GET_AuthClientCredentialsIntrospect_Response_401 = Problem;
export type GET_AuthClientCredentialsIntrospect_Response_422 = HTTPValidationError;

export type GET_Availability_Response = GET_Availability_Response_200 | GET_Availability_Response_401 | GET_Availability_Response_422;

export type GET_Availability_Response_200 = DomainAvailabilityList;
export type GET_Availability_Response_401 = Problem;
export type GET_Availability_Response_422 = HTTPValidationError;

export type GET_AvailabilityStream_Response = GET_AvailabilityStream_Response_401 | GET_AvailabilityStream_Response_422;

export type GET_AvailabilityStream_Response_401 = Problem;
export type GET_AvailabilityStream_Response_422 = HTTPValidationError;

export type GET_Contacts_Response = GET_Contacts_Response_200 | GET_Contacts_Response_422;

export type GET_Contacts_Response_200 = Pagination_Contact;
export type GET_Contacts_Response_422 = HTTPValidationError;

export type GET_ContactsAttributeSets_Response = GET_ContactsAttributeSets_Response_200 | GET_ContactsAttributeSets_Response_422;

export type GET_ContactsAttributeSets_Response_200 = Pagination_ContactAttributeSet;
export type GET_ContactsAttributeSets_Response_422 = HTTPValidationError;

export type GET_ContactsAttributeSetsByContactAttributeSetId_Response = GET_ContactsAttributeSetsByContactAttributeSetId_Response_200 | GET_ContactsAttributeSetsByContactAttributeSetId_Response_404 | GET_ContactsAttributeSetsByContactAttributeSetId_Response_422;

export type GET_ContactsAttributeSetsByContactAttributeSetId_Response_200 = ContactAttributeSet;
export type GET_ContactsAttributeSetsByContactAttributeSetId_Response_404 = Problem;
export type GET_ContactsAttributeSetsByContactAttributeSetId_Response_422 = HTTPValidationError;

export type GET_ContactsByContactId_Response = GET_ContactsByContactId_Response_200 | GET_ContactsByContactId_Response_404 | GET_ContactsByContactId_Response_422;

export type GET_ContactsByContactId_Response_200 = Contact;
export type GET_ContactsByContactId_Response_404 = Problem;
export type GET_ContactsByContactId_Response_422 = HTTPValidationError;

export type GET_ContactsByContactIdVerification_Response = GET_ContactsByContactIdVerification_Response_200 | GET_ContactsByContactIdVerification_Response_401 | GET_ContactsByContactIdVerification_Response_404 | GET_ContactsByContactIdVerification_Response_422;

export type GET_ContactsByContactIdVerification_Response_200 = ContactVerification;
export type GET_ContactsByContactIdVerification_Response_401 = Problem;
export type GET_ContactsByContactIdVerification_Response_404 = Problem;
export type GET_ContactsByContactIdVerification_Response_422 = HTTPValidationError;

export type GET_ContactsByContactIdVerifications_Response = GET_ContactsByContactIdVerifications_Response_200 | GET_ContactsByContactIdVerifications_Response_401 | GET_ContactsByContactIdVerifications_Response_404 | GET_ContactsByContactIdVerifications_Response_422 | GET_ContactsByContactIdVerifications_Response_502;

export type GET_ContactsByContactIdVerifications_Response_200 = ContactAttestRes;
export type GET_ContactsByContactIdVerifications_Response_401 = Problem;
export type GET_ContactsByContactIdVerifications_Response_404 = Problem;
export type GET_ContactsByContactIdVerifications_Response_422 = HTTPValidationError;
export type GET_ContactsByContactIdVerifications_Response_502 = Problem;

export type GET_ContactsVerification_Response = GET_ContactsVerification_Response_200 | GET_ContactsVerification_Response_401 | GET_ContactsVerification_Response_404 | GET_ContactsVerification_Response_422;

export type GET_ContactsVerification_Response_200 = Contact;
export type GET_ContactsVerification_Response_401 = Problem;
export type GET_ContactsVerification_Response_404 = Problem;
export type GET_ContactsVerification_Response_422 = HTTPValidationError;

export type GET_ContactsVerify_Response = GET_ContactsVerify_Response_422;

export type GET_ContactsVerify_Response_422 = HTTPValidationError;

export type GET_Dns_Response = GET_Dns_Response_200 | GET_Dns_Response_422;

export type GET_Dns_Response_200 = Pagination_DnsZone;
export type GET_Dns_Response_422 = HTTPValidationError;

export type GET_DnsByZoneName_Response = GET_DnsByZoneName_Response_200 | GET_DnsByZoneName_Response_422;

export type GET_DnsByZoneName_Response_200 = DnsZone;
export type GET_DnsByZoneName_Response_422 = HTTPValidationError;

export type GET_DnsByZoneNameDomainForwards_Response = GET_DnsByZoneNameDomainForwards_Response_200 | GET_DnsByZoneNameDomainForwards_Response_401 | GET_DnsByZoneNameDomainForwards_Response_403 | GET_DnsByZoneNameDomainForwards_Response_422;

export type GET_DnsByZoneNameDomainForwards_Response_200 = DomainForwardZone;
export type GET_DnsByZoneNameDomainForwards_Response_401 = Problem;
export type GET_DnsByZoneNameDomainForwards_Response_403 = Problem;
export type GET_DnsByZoneNameDomainForwards_Response_422 = HTTPValidationError;

export type GET_DnsByZoneNameEmailForwards_Response = GET_DnsByZoneNameEmailForwards_Response_200 | GET_DnsByZoneNameEmailForwards_Response_401 | GET_DnsByZoneNameEmailForwards_Response_403 | GET_DnsByZoneNameEmailForwards_Response_422;

export type GET_DnsByZoneNameEmailForwards_Response_200 = EmailForwardZone;
export type GET_DnsByZoneNameEmailForwards_Response_401 = Problem;
export type GET_DnsByZoneNameEmailForwards_Response_403 = Problem;
export type GET_DnsByZoneNameEmailForwards_Response_422 = HTTPValidationError;

export type GET_DnsDomainForwards_Response = GET_DnsDomainForwards_Response_200 | GET_DnsDomainForwards_Response_401 | GET_DnsDomainForwards_Response_403 | GET_DnsDomainForwards_Response_422;

export type GET_DnsDomainForwards_Response_200 = Pagination_DomainForwardZone;
export type GET_DnsDomainForwards_Response_401 = Problem;
export type GET_DnsDomainForwards_Response_403 = Problem;
export type GET_DnsDomainForwards_Response_422 = HTTPValidationError;

export type GET_DnsEmailForwards_Response = GET_DnsEmailForwards_Response_200 | GET_DnsEmailForwards_Response_401 | GET_DnsEmailForwards_Response_403 | GET_DnsEmailForwards_Response_422;

export type GET_DnsEmailForwards_Response_200 = Pagination_EmailForwardZone;
export type GET_DnsEmailForwards_Response_401 = Problem;
export type GET_DnsEmailForwards_Response_403 = Problem;
export type GET_DnsEmailForwards_Response_422 = HTTPValidationError;

export type GET_DnsSummary_Response = GET_DnsSummary_Response_200 | GET_DnsSummary_Response_422;

export type GET_DnsSummary_Response_200 = DnsZoneSummary;
export type GET_DnsSummary_Response_422 = HTTPValidationError;

export type GET_DomainForwards_Response = GET_DomainForwards_Response_200 | GET_DomainForwards_Response_401 | GET_DomainForwards_Response_403 | GET_DomainForwards_Response_422;

export type GET_DomainForwards_Response_200 = Pagination_DomainForward;
export type GET_DomainForwards_Response_401 = Problem;
export type GET_DomainForwards_Response_403 = Problem;
export type GET_DomainForwards_Response_422 = HTTPValidationError;

export type GET_DomainForwardsByHostname_Response = GET_DomainForwardsByHostname_Response_200 | GET_DomainForwardsByHostname_Response_401 | GET_DomainForwardsByHostname_Response_403 | GET_DomainForwardsByHostname_Response_404 | GET_DomainForwardsByHostname_Response_422;

export type GET_DomainForwardsByHostname_Response_200 = DomainForward;
export type GET_DomainForwardsByHostname_Response_401 = Problem;
export type GET_DomainForwardsByHostname_Response_403 = Problem;
export type GET_DomainForwardsByHostname_Response_404 = Problem;
export type GET_DomainForwardsByHostname_Response_422 = HTTPValidationError;

export type GET_DomainForwardsByHostnameByProtocol_Response = GET_DomainForwardsByHostnameByProtocol_Response_200 | GET_DomainForwardsByHostnameByProtocol_Response_401 | GET_DomainForwardsByHostnameByProtocol_Response_403 | GET_DomainForwardsByHostnameByProtocol_Response_404 | GET_DomainForwardsByHostnameByProtocol_Response_422;

export type GET_DomainForwardsByHostnameByProtocol_Response_200 = DomainForwardSet;
export type GET_DomainForwardsByHostnameByProtocol_Response_401 = Problem;
export type GET_DomainForwardsByHostnameByProtocol_Response_403 = Problem;
export type GET_DomainForwardsByHostnameByProtocol_Response_404 = Problem;
export type GET_DomainForwardsByHostnameByProtocol_Response_422 = HTTPValidationError;

export type GET_DomainForwardsMetrics_Response = GET_DomainForwardsMetrics_Response_200 | GET_DomainForwardsMetrics_Response_401 | GET_DomainForwardsMetrics_Response_403 | GET_DomainForwardsMetrics_Response_422 | GET_DomainForwardsMetrics_Response_503;

export type GET_DomainForwardsMetrics_Response_200 = DomainForwardMetrics;
export type GET_DomainForwardsMetrics_Response_401 = Problem;
export type GET_DomainForwardsMetrics_Response_403 = Problem;
export type GET_DomainForwardsMetrics_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetrics_Response_503 = Problem;

export type GET_DomainForwardsMetricsBrowser_Response = GET_DomainForwardsMetricsBrowser_Response_200 | GET_DomainForwardsMetricsBrowser_Response_401 | GET_DomainForwardsMetricsBrowser_Response_403 | GET_DomainForwardsMetricsBrowser_Response_422 | GET_DomainForwardsMetricsBrowser_Response_503;

export type GET_DomainForwardsMetricsBrowser_Response_200 = DomainForwardBrowserStats;
export type GET_DomainForwardsMetricsBrowser_Response_401 = Problem;
export type GET_DomainForwardsMetricsBrowser_Response_403 = Problem;
export type GET_DomainForwardsMetricsBrowser_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsBrowser_Response_503 = Problem;

export type GET_DomainForwardsMetricsGeo_Response = GET_DomainForwardsMetricsGeo_Response_200 | GET_DomainForwardsMetricsGeo_Response_401 | GET_DomainForwardsMetricsGeo_Response_403 | GET_DomainForwardsMetricsGeo_Response_422 | GET_DomainForwardsMetricsGeo_Response_503;

export type GET_DomainForwardsMetricsGeo_Response_200 = DomainForwardGeoStats;
export type GET_DomainForwardsMetricsGeo_Response_401 = Problem;
export type GET_DomainForwardsMetricsGeo_Response_403 = Problem;
export type GET_DomainForwardsMetricsGeo_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsGeo_Response_503 = Problem;

export type GET_DomainForwardsMetricsPlatform_Response = GET_DomainForwardsMetricsPlatform_Response_200 | GET_DomainForwardsMetricsPlatform_Response_401 | GET_DomainForwardsMetricsPlatform_Response_403 | GET_DomainForwardsMetricsPlatform_Response_422 | GET_DomainForwardsMetricsPlatform_Response_503;

export type GET_DomainForwardsMetricsPlatform_Response_200 = DomainForwardPlatformStats;
export type GET_DomainForwardsMetricsPlatform_Response_401 = Problem;
export type GET_DomainForwardsMetricsPlatform_Response_403 = Problem;
export type GET_DomainForwardsMetricsPlatform_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsPlatform_Response_503 = Problem;

export type GET_DomainForwardsMetricsReferrer_Response = GET_DomainForwardsMetricsReferrer_Response_200 | GET_DomainForwardsMetricsReferrer_Response_401 | GET_DomainForwardsMetricsReferrer_Response_403 | GET_DomainForwardsMetricsReferrer_Response_422 | GET_DomainForwardsMetricsReferrer_Response_503;

export type GET_DomainForwardsMetricsReferrer_Response_200 = DomainForwardReferrerStats;
export type GET_DomainForwardsMetricsReferrer_Response_401 = Problem;
export type GET_DomainForwardsMetricsReferrer_Response_403 = Problem;
export type GET_DomainForwardsMetricsReferrer_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsReferrer_Response_503 = Problem;

export type GET_DomainForwardsMetricsStatusCode_Response = GET_DomainForwardsMetricsStatusCode_Response_200 | GET_DomainForwardsMetricsStatusCode_Response_401 | GET_DomainForwardsMetricsStatusCode_Response_403 | GET_DomainForwardsMetricsStatusCode_Response_422 | GET_DomainForwardsMetricsStatusCode_Response_503;

export type GET_DomainForwardsMetricsStatusCode_Response_200 = DomainForwardStatusCodeStats;
export type GET_DomainForwardsMetricsStatusCode_Response_401 = Problem;
export type GET_DomainForwardsMetricsStatusCode_Response_403 = Problem;
export type GET_DomainForwardsMetricsStatusCode_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsStatusCode_Response_503 = Problem;

export type GET_DomainForwardsMetricsTimeSeries_Response = GET_DomainForwardsMetricsTimeSeries_Response_200 | GET_DomainForwardsMetricsTimeSeries_Response_401 | GET_DomainForwardsMetricsTimeSeries_Response_403 | GET_DomainForwardsMetricsTimeSeries_Response_422 | GET_DomainForwardsMetricsTimeSeries_Response_503;

export type GET_DomainForwardsMetricsTimeSeries_Response_200 = DomainForwardMetricsTimeSeries;
export type GET_DomainForwardsMetricsTimeSeries_Response_401 = Problem;
export type GET_DomainForwardsMetricsTimeSeries_Response_403 = Problem;
export type GET_DomainForwardsMetricsTimeSeries_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsTimeSeries_Response_503 = Problem;

export type GET_DomainForwardsMetricsUserAgent_Response = GET_DomainForwardsMetricsUserAgent_Response_200 | GET_DomainForwardsMetricsUserAgent_Response_401 | GET_DomainForwardsMetricsUserAgent_Response_403 | GET_DomainForwardsMetricsUserAgent_Response_422 | GET_DomainForwardsMetricsUserAgent_Response_503;

export type GET_DomainForwardsMetricsUserAgent_Response_200 = DomainForwardUserAgentStats;
export type GET_DomainForwardsMetricsUserAgent_Response_401 = Problem;
export type GET_DomainForwardsMetricsUserAgent_Response_403 = Problem;
export type GET_DomainForwardsMetricsUserAgent_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsUserAgent_Response_503 = Problem;

export type GET_DomainForwardsMetricsVisitsByKey_Response = GET_DomainForwardsMetricsVisitsByKey_Response_200 | GET_DomainForwardsMetricsVisitsByKey_Response_401 | GET_DomainForwardsMetricsVisitsByKey_Response_403 | GET_DomainForwardsMetricsVisitsByKey_Response_422 | GET_DomainForwardsMetricsVisitsByKey_Response_503;

export type GET_DomainForwardsMetricsVisitsByKey_Response_200 = DomainForwardVisitsByKey;
export type GET_DomainForwardsMetricsVisitsByKey_Response_401 = Problem;
export type GET_DomainForwardsMetricsVisitsByKey_Response_403 = Problem;
export type GET_DomainForwardsMetricsVisitsByKey_Response_422 = HTTPValidationError;
export type GET_DomainForwardsMetricsVisitsByKey_Response_503 = Problem;

export type GET_DomainSearchSuggest_Response = GET_DomainSearchSuggest_Response_200 | GET_DomainSearchSuggest_Response_401 | GET_DomainSearchSuggest_Response_422 | GET_DomainSearchSuggest_Response_502;

export type GET_DomainSearchSuggest_Response_200 = DomainSearch;
export type GET_DomainSearchSuggest_Response_401 = Problem;
export type GET_DomainSearchSuggest_Response_422 = HTTPValidationError;
export type GET_DomainSearchSuggest_Response_502 = Problem;

export type GET_Domains_Response = GET_Domains_Response_200 | GET_Domains_Response_422;

export type GET_Domains_Response_200 = Pagination_Domain;
export type GET_Domains_Response_422 = HTTPValidationError;

export type GET_DomainsByDomainReference_Response = GET_DomainsByDomainReference_Response_200 | GET_DomainsByDomainReference_Response_404 | GET_DomainsByDomainReference_Response_422;

export type GET_DomainsByDomainReference_Response_200 = Domain;
export type GET_DomainsByDomainReference_Response_404 = Problem;
export type GET_DomainsByDomainReference_Response_422 = HTTPValidationError;

export type GET_DomainsByDomainReferenceDnssec_Response = GET_DomainsByDomainReferenceDnssec_Response_200 | GET_DomainsByDomainReferenceDnssec_Response_404 | GET_DomainsByDomainReferenceDnssec_Response_422;

export type GET_DomainsByDomainReferenceDnssec_Response_200 = DomainDnssecData[];
export type GET_DomainsByDomainReferenceDnssec_Response_404 = Problem;
export type GET_DomainsByDomainReferenceDnssec_Response_422 = HTTPValidationError;

export type GET_DomainsCheck_Response = GET_DomainsCheck_Response_200 | GET_DomainsCheck_Response_422;

export type GET_DomainsCheck_Response_200 = DomainCheck;
export type GET_DomainsCheck_Response_422 = HTTPValidationError;

export type GET_DomainsSummary_Response = GET_DomainsSummary_Response_200 | GET_DomainsSummary_Response_422;

export type GET_DomainsSummary_Response_200 = DomainSummary;
export type GET_DomainsSummary_Response_422 = HTTPValidationError;

export type GET_DomainsTldSpecificNoApplicantDeclaration_Response = GET_DomainsTldSpecificNoApplicantDeclaration_Response_200 | GET_DomainsTldSpecificNoApplicantDeclaration_Response_404 | GET_DomainsTldSpecificNoApplicantDeclaration_Response_422;

export type GET_DomainsTldSpecificNoApplicantDeclaration_Response_200 = NorIdDeclaration;
export type GET_DomainsTldSpecificNoApplicantDeclaration_Response_404 = Problem;
export type GET_DomainsTldSpecificNoApplicantDeclaration_Response_422 = HTTPValidationError;

export type GET_EmailForwards_Response = GET_EmailForwards_Response_200 | GET_EmailForwards_Response_401 | GET_EmailForwards_Response_403 | GET_EmailForwards_Response_422;

export type GET_EmailForwards_Response_200 = Pagination_EmailForward;
export type GET_EmailForwards_Response_401 = Problem;
export type GET_EmailForwards_Response_403 = Problem;
export type GET_EmailForwards_Response_422 = HTTPValidationError;

export type GET_EmailForwardsByEmailForwardId_Response = GET_EmailForwardsByEmailForwardId_Response_200 | GET_EmailForwardsByEmailForwardId_Response_401 | GET_EmailForwardsByEmailForwardId_Response_403 | GET_EmailForwardsByEmailForwardId_Response_404 | GET_EmailForwardsByEmailForwardId_Response_422;

export type GET_EmailForwardsByEmailForwardId_Response_200 = EmailForward;
export type GET_EmailForwardsByEmailForwardId_Response_401 = Problem;
export type GET_EmailForwardsByEmailForwardId_Response_403 = Problem;
export type GET_EmailForwardsByEmailForwardId_Response_404 = Problem;
export type GET_EmailForwardsByEmailForwardId_Response_422 = HTTPValidationError;

export type GET_EmailForwardsByEmailForwardIdMetrics_Response = GET_EmailForwardsByEmailForwardIdMetrics_Response_200 | GET_EmailForwardsByEmailForwardIdMetrics_Response_401 | GET_EmailForwardsByEmailForwardIdMetrics_Response_403 | GET_EmailForwardsByEmailForwardIdMetrics_Response_404 | GET_EmailForwardsByEmailForwardIdMetrics_Response_422;

export type GET_EmailForwardsByEmailForwardIdMetrics_Response_200 = EmailForwardMetrics;
export type GET_EmailForwardsByEmailForwardIdMetrics_Response_401 = Problem;
export type GET_EmailForwardsByEmailForwardIdMetrics_Response_403 = Problem;
export type GET_EmailForwardsByEmailForwardIdMetrics_Response_404 = Problem;
export type GET_EmailForwardsByEmailForwardIdMetrics_Response_422 = HTTPValidationError;

export type GET_Events_Response = GET_Events_Response_200 | GET_Events_Response_401 | GET_Events_Response_422;

export type GET_Events_Response_200 = Pagination_Event;
export type GET_Events_Response_401 = Problem;
export type GET_Events_Response_422 = HTTPValidationError;

export type GET_EventsByEventId_Response = GET_EventsByEventId_Response_200 | GET_EventsByEventId_Response_401 | GET_EventsByEventId_Response_404 | GET_EventsByEventId_Response_422;

export type GET_EventsByEventId_Response_200 = EventResponse;
export type GET_EventsByEventId_Response_401 = Problem;
export type GET_EventsByEventId_Response_404 = Problem;
export type GET_EventsByEventId_Response_422 = HTTPValidationError;

export type GET_HostsByHostReference_Response = GET_HostsByHostReference_Response_200 | GET_HostsByHostReference_Response_401 | GET_HostsByHostReference_Response_403 | GET_HostsByHostReference_Response_404 | GET_HostsByHostReference_Response_422;

export type GET_HostsByHostReference_Response_200 = Host;
export type GET_HostsByHostReference_Response_401 = Problem;
export type GET_HostsByHostReference_Response_403 = Problem;
export type GET_HostsByHostReference_Response_404 = Problem;
export type GET_HostsByHostReference_Response_422 = HTTPValidationError;

export type GET_JobByJobId_Response = GET_JobByJobId_Response_200 | GET_JobByJobId_Response_404 | GET_JobByJobId_Response_422;

export type GET_JobByJobId_Response_200 = Job;
export type GET_JobByJobId_Response_404 = Problem;
export type GET_JobByJobId_Response_422 = HTTPValidationError;

export type GET_Jobs_Response = GET_Jobs_Response_200 | GET_Jobs_Response_422;

export type GET_Jobs_Response_200 = PageResponse_JobBatchMetadata;
export type GET_Jobs_Response_422 = HTTPValidationError;

export type GET_JobsByBatchId_Response = GET_JobsByBatchId_Response_200 | GET_JobsByBatchId_Response_404 | GET_JobsByBatchId_Response_422 | GET_JobsByBatchId_Response_503;

export type GET_JobsByBatchId_Response_200 = JobBatchStatus;
export type GET_JobsByBatchId_Response_404 = Problem;
export type GET_JobsByBatchId_Response_422 = HTTPValidationError;
export type GET_JobsByBatchId_Response_503 = Problem;

export type GET_JobsByBatchIdJobs_Response = GET_JobsByBatchIdJobs_Response_200 | GET_JobsByBatchIdJobs_Response_404 | GET_JobsByBatchIdJobs_Response_422 | GET_JobsByBatchIdJobs_Response_503;

export type GET_JobsByBatchIdJobs_Response_200 = PageResponse_Job;
export type GET_JobsByBatchIdJobs_Response_404 = Problem;
export type GET_JobsByBatchIdJobs_Response_422 = HTTPValidationError;
export type GET_JobsByBatchIdJobs_Response_503 = Problem;

export type GET_Organizations_Response = GET_Organizations_Response_200 | GET_Organizations_Response_401 | GET_Organizations_Response_403 | GET_Organizations_Response_422;

export type GET_Organizations_Response_200 = Pagination_Organization;
export type GET_Organizations_Response_401 = Problem;
export type GET_Organizations_Response_403 = Problem;
export type GET_Organizations_Response_422 = HTTPValidationError;

export type GET_OrganizationsAttributes_Response = GET_OrganizationsAttributes_Response_200 | GET_OrganizationsAttributes_Response_401 | GET_OrganizationsAttributes_Response_403 | GET_OrganizationsAttributes_Response_422;

export type GET_OrganizationsAttributes_Response_200 = OrganizationAttribute2[];
export type GET_OrganizationsAttributes_Response_401 = Problem;
export type GET_OrganizationsAttributes_Response_403 = Problem;
export type GET_OrganizationsAttributes_Response_422 = HTTPValidationError;

export type GET_OrganizationsByOrganizationId_Response = GET_OrganizationsByOrganizationId_Response_200 | GET_OrganizationsByOrganizationId_Response_401 | GET_OrganizationsByOrganizationId_Response_403 | GET_OrganizationsByOrganizationId_Response_422;

export type GET_OrganizationsByOrganizationId_Response_200 = OrganizationWithBillingData;
export type GET_OrganizationsByOrganizationId_Response_401 = Problem;
export type GET_OrganizationsByOrganizationId_Response_403 = Problem;
export type GET_OrganizationsByOrganizationId_Response_422 = HTTPValidationError;

export type GET_OrganizationsByOrganizationIdAttributes_Response = GET_OrganizationsByOrganizationIdAttributes_Response_200 | GET_OrganizationsByOrganizationIdAttributes_Response_401 | GET_OrganizationsByOrganizationIdAttributes_Response_403 | GET_OrganizationsByOrganizationIdAttributes_Response_422;

export type GET_OrganizationsByOrganizationIdAttributes_Response_200 = OrganizationAttribute2[];
export type GET_OrganizationsByOrganizationIdAttributes_Response_401 = Problem;
export type GET_OrganizationsByOrganizationIdAttributes_Response_403 = Problem;
export type GET_OrganizationsByOrganizationIdAttributes_Response_422 = HTTPValidationError;

export type GET_OrganizationsByOrganizationIdBillingInvoices_Response = GET_OrganizationsByOrganizationIdBillingInvoices_Response_200 | GET_OrganizationsByOrganizationIdBillingInvoices_Response_422;

export type GET_OrganizationsByOrganizationIdBillingInvoices_Response_200 = Pagination_Invoice;
export type GET_OrganizationsByOrganizationIdBillingInvoices_Response_422 = HTTPValidationError;

export type GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response = GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_200 | GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_401 | GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_403 | GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_422;

export type GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_200 = GetPrices;
export type GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_401 = Problem;
export type GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_403 = Problem;
export type GET_OrganizationsByOrganizationIdPricingProductTypeByProductType_Response_422 = HTTPValidationError;

export type GET_OrganizationsByOrganizationIdTransactions_Response = GET_OrganizationsByOrganizationIdTransactions_Response_200 | GET_OrganizationsByOrganizationIdTransactions_Response_401 | GET_OrganizationsByOrganizationIdTransactions_Response_403 | GET_OrganizationsByOrganizationIdTransactions_Response_422;

export type GET_OrganizationsByOrganizationIdTransactions_Response_200 = Pagination_BillingTransaction;
export type GET_OrganizationsByOrganizationIdTransactions_Response_401 = Problem;
export type GET_OrganizationsByOrganizationIdTransactions_Response_403 = Problem;
export type GET_OrganizationsByOrganizationIdTransactions_Response_422 = HTTPValidationError;

export type GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response = GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_200 | GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_401 | GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_403 | GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_422;

export type GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_200 = BillingTransaction;
export type GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_401 = Problem;
export type GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_403 = Problem;
export type GET_OrganizationsByOrganizationIdTransactionsByTransactionId_Response_422 = HTTPValidationError;

export type GET_OrganizationsIpRestrictions_Response = GET_OrganizationsIpRestrictions_Response_200 | GET_OrganizationsIpRestrictions_Response_401 | GET_OrganizationsIpRestrictions_Response_403 | GET_OrganizationsIpRestrictions_Response_422;

export type GET_OrganizationsIpRestrictions_Response_200 = IpRestriction[];
export type GET_OrganizationsIpRestrictions_Response_401 = Problem;
export type GET_OrganizationsIpRestrictions_Response_403 = Problem;
export type GET_OrganizationsIpRestrictions_Response_422 = HTTPValidationError;

export type GET_OrganizationsIpRestrictionsByIpRestrictionId_Response = GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_200 | GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_401 | GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_403 | GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_422;

export type GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_200 = IpRestriction;
export type GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_401 = Problem;
export type GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_403 = Problem;
export type GET_OrganizationsIpRestrictionsByIpRestrictionId_Response_422 = HTTPValidationError;

export type GET_OrganizationsRolePermissions_Response = GET_OrganizationsRolePermissions_Response_200 | GET_OrganizationsRolePermissions_Response_401 | GET_OrganizationsRolePermissions_Response_403 | GET_OrganizationsRolePermissions_Response_422;

export type GET_OrganizationsRolePermissions_Response_200 = PublicPermissionSet;
export type GET_OrganizationsRolePermissions_Response_401 = Problem;
export type GET_OrganizationsRolePermissions_Response_403 = Problem;
export type GET_OrganizationsRolePermissions_Response_422 = HTTPValidationError;

export type GET_OrganizationsRoles_Response = GET_OrganizationsRoles_Response_200 | GET_OrganizationsRoles_Response_401 | GET_OrganizationsRoles_Response_403 | GET_OrganizationsRoles_Response_422;

export type GET_OrganizationsRoles_Response_200 = PublicRoleDefinition[];
export type GET_OrganizationsRoles_Response_401 = Problem;
export type GET_OrganizationsRoles_Response_403 = Problem;
export type GET_OrganizationsRoles_Response_422 = HTTPValidationError;

export type GET_OrganizationsRolesByLabel_Response = GET_OrganizationsRolesByLabel_Response_200 | GET_OrganizationsRolesByLabel_Response_401 | GET_OrganizationsRolesByLabel_Response_403 | GET_OrganizationsRolesByLabel_Response_404 | GET_OrganizationsRolesByLabel_Response_422;

export type GET_OrganizationsRolesByLabel_Response_200 = PublicRoleDefinition;
export type GET_OrganizationsRolesByLabel_Response_401 = Problem;
export type GET_OrganizationsRolesByLabel_Response_403 = Problem;
export type GET_OrganizationsRolesByLabel_Response_404 = Problem;
export type GET_OrganizationsRolesByLabel_Response_422 = HTTPValidationError;

export type GET_OrganizationsUsers_Response = GET_OrganizationsUsers_Response_200 | GET_OrganizationsUsers_Response_401 | GET_OrganizationsUsers_Response_403 | GET_OrganizationsUsers_Response_422;

export type GET_OrganizationsUsers_Response_200 = Pagination_UserPublicWithRole;
export type GET_OrganizationsUsers_Response_401 = Problem;
export type GET_OrganizationsUsers_Response_403 = Problem;
export type GET_OrganizationsUsers_Response_422 = HTTPValidationError;

export type GET_Parking_Response = GET_Parking_Response_200 | GET_Parking_Response_401 | GET_Parking_Response_403 | GET_Parking_Response_422;

export type GET_Parking_Response_200 = PageResponse_Parking;
export type GET_Parking_Response_401 = Problem;
export type GET_Parking_Response_403 = Problem;
export type GET_Parking_Response_422 = HTTPValidationError;

export type GET_ParkingByParkingReferenceMetrics_Response = GET_ParkingByParkingReferenceMetrics_Response_200 | GET_ParkingByParkingReferenceMetrics_Response_401 | GET_ParkingByParkingReferenceMetrics_Response_403 | GET_ParkingByParkingReferenceMetrics_Response_404 | GET_ParkingByParkingReferenceMetrics_Response_422;

export type GET_ParkingByParkingReferenceMetrics_Response_200 = ParkingMetrics;
export type GET_ParkingByParkingReferenceMetrics_Response_401 = Problem;
export type GET_ParkingByParkingReferenceMetrics_Response_403 = Problem;
export type GET_ParkingByParkingReferenceMetrics_Response_404 = Problem;
export type GET_ParkingByParkingReferenceMetrics_Response_422 = HTTPValidationError;

export type GET_ParkingMetrics_Response = GET_ParkingMetrics_Response_200 | GET_ParkingMetrics_Response_401 | GET_ParkingMetrics_Response_403 | GET_ParkingMetrics_Response_422;

export type GET_ParkingMetrics_Response_200 = ParkingTotalMetrics;
export type GET_ParkingMetrics_Response_401 = Problem;
export type GET_ParkingMetrics_Response_403 = Problem;
export type GET_ParkingMetrics_Response_422 = HTTPValidationError;

export type GET_ParkingSignupStatus_Response = GET_ParkingSignupStatus_Response_200 | GET_ParkingSignupStatus_Response_401 | GET_ParkingSignupStatus_Response_403 | GET_ParkingSignupStatus_Response_422;

export type GET_ParkingSignupStatus_Response_200 = ParkingSignupStatus;
export type GET_ParkingSignupStatus_Response_401 = Problem;
export type GET_ParkingSignupStatus_Response_403 = Problem;
export type GET_ParkingSignupStatus_Response_422 = HTTPValidationError;

export type GET_Reports_Response = GET_Reports_Response_200 | GET_Reports_Response_422;

export type GET_Reports_Response_200 = PublicReportListRes;
export type GET_Reports_Response_422 = HTTPValidationError;

export type GET_ReportsByReportId_Response = GET_ReportsByReportId_Response_200 | GET_ReportsByReportId_Response_422;

export type GET_ReportsByReportId_Response_200 = PublicReportRes;
export type GET_ReportsByReportId_Response_422 = HTTPValidationError;

export type GET_ReportsByReportIdDownload_Response = GET_ReportsByReportIdDownload_Response_422;

export type GET_ReportsByReportIdDownload_Response_422 = HTTPValidationError;

export type GET_Tags_Response = GET_Tags_Response_200 | GET_Tags_Response_401 | GET_Tags_Response_422;

export type GET_Tags_Response_200 = Pagination_Tag;
export type GET_Tags_Response_401 = Problem;
export type GET_Tags_Response_422 = HTTPValidationError;

export type GET_TagsByTagId_Response = GET_TagsByTagId_Response_200 | GET_TagsByTagId_Response_401 | GET_TagsByTagId_Response_404 | GET_TagsByTagId_Response_422;

export type GET_TagsByTagId_Response_200 = Tag;
export type GET_TagsByTagId_Response_401 = Problem;
export type GET_TagsByTagId_Response_404 = Problem;
export type GET_TagsByTagId_Response_422 = HTTPValidationError;

export type GET_Tlds_Response = GET_Tlds_Response_422;

export type GET_Tlds_Response_422 = HTTPValidationError;

export type GET_TldsByTld_Response = GET_TldsByTld_Response_200 | GET_TldsByTld_Response_404 | GET_TldsByTld_Response_422;

export type GET_TldsByTld_Response_200 = TldSpecification;
export type GET_TldsByTld_Response_404 = Problem;
export type GET_TldsByTld_Response_422 = HTTPValidationError;

export type GET_TldsPortfolio_Response = GET_TldsPortfolio_Response_200 | GET_TldsPortfolio_Response_422;

export type GET_TldsPortfolio_Response_200 = TldResponseShort[];
export type GET_TldsPortfolio_Response_422 = HTTPValidationError;

export type GET_UsersByUserId_Response = GET_UsersByUserId_Response_200 | GET_UsersByUserId_Response_422;

export type GET_UsersByUserId_Response_200 = UserPublicWithAttributes;
export type GET_UsersByUserId_Response_422 = HTTPValidationError;

export type GET_UsersByUserIdPermissions_Response = GET_UsersByUserIdPermissions_Response_200 | GET_UsersByUserIdPermissions_Response_422;

export type GET_UsersByUserIdPermissions_Response_200 = PublicPermissionSet;
export type GET_UsersByUserIdPermissions_Response_422 = HTTPValidationError;

export type GET_UsersByUserIdRole_Response = GET_UsersByUserIdRole_Response_200 | GET_UsersByUserIdRole_Response_422;

export type GET_UsersByUserIdRole_Response_200 = PublicRoleAssignment;
export type GET_UsersByUserIdRole_Response_422 = HTTPValidationError;

export type GET_UsersMe_Response = GET_UsersMe_Response_200 | GET_UsersMe_Response_422;

export type GET_UsersMe_Response_200 = UserProfile;
export type GET_UsersMe_Response_422 = HTTPValidationError;

export type GET_VanityNameserverSets_Response = GET_VanityNameserverSets_Response_200 | GET_VanityNameserverSets_Response_422;

export type GET_VanityNameserverSets_Response_200 = ListVanityNameserverSetsRes;
export type GET_VanityNameserverSets_Response_422 = HTTPValidationError;

export type GET_VanityNameserverSetsBySetId_Response = GET_VanityNameserverSetsBySetId_Response_200 | GET_VanityNameserverSetsBySetId_Response_422;

export type GET_VanityNameserverSetsBySetId_Response_200 = VanityNameserverSetSummaryDTO;
export type GET_VanityNameserverSetsBySetId_Response_422 = HTTPValidationError;

export type GET_VanityNameserverSetsBySetIdZones_Response = GET_VanityNameserverSetsBySetIdZones_Response_200 | GET_VanityNameserverSetsBySetIdZones_Response_422;

export type GET_VanityNameserverSetsBySetIdZones_Response_200 = ListZonesReferencingSetRes;
export type GET_VanityNameserverSetsBySetIdZones_Response_422 = HTTPValidationError;

export type PATCH_AiConciergeConversationsByConversationId_Response = PATCH_AiConciergeConversationsByConversationId_Response_200 | PATCH_AiConciergeConversationsByConversationId_Response_401 | PATCH_AiConciergeConversationsByConversationId_Response_404 | PATCH_AiConciergeConversationsByConversationId_Response_422 | PATCH_AiConciergeConversationsByConversationId_Response_502;

export type PATCH_AiConciergeConversationsByConversationId_Response_200 = Conversation;
export type PATCH_AiConciergeConversationsByConversationId_Response_401 = Problem;
export type PATCH_AiConciergeConversationsByConversationId_Response_404 = Problem;
export type PATCH_AiConciergeConversationsByConversationId_Response_422 = HTTPValidationError;
export type PATCH_AiConciergeConversationsByConversationId_Response_502 = Problem;

export type PATCH_AiConciergeMemoryFactsByFactId_Response = PATCH_AiConciergeMemoryFactsByFactId_Response_200 | PATCH_AiConciergeMemoryFactsByFactId_Response_401 | PATCH_AiConciergeMemoryFactsByFactId_Response_404 | PATCH_AiConciergeMemoryFactsByFactId_Response_422 | PATCH_AiConciergeMemoryFactsByFactId_Response_502;

export type PATCH_AiConciergeMemoryFactsByFactId_Response_200 = MemoryFact;
export type PATCH_AiConciergeMemoryFactsByFactId_Response_401 = Problem;
export type PATCH_AiConciergeMemoryFactsByFactId_Response_404 = Problem;
export type PATCH_AiConciergeMemoryFactsByFactId_Response_422 = HTTPValidationError;
export type PATCH_AiConciergeMemoryFactsByFactId_Response_502 = Problem;

export type PATCH_ContactsAttributeSetsByContactAttributeSetId_Response = PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_200 | PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_404 | PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_409 | PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_422;

export type PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_200 = ContactAttributeSet;
export type PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_404 = Problem;
export type PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_409 = Problem;
export type PATCH_ContactsAttributeSetsByContactAttributeSetId_Response_422 = HTTPValidationError;

export type PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response = PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_200 | PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_404 | PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_409 | PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_422;

export type PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_200 = ContactAttributeLink;
export type PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_404 = Problem;
export type PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_409 = Problem;
export type PATCH_ContactsByContactIdLinkByContactAttributeSetId_Response_422 = HTTPValidationError;

export type PATCH_DnsByZoneNameRecords_Response = PATCH_DnsByZoneNameRecords_Response_400 | PATCH_DnsByZoneNameRecords_Response_422;

export type PATCH_DnsByZoneNameRecords_Response_400 = Problem;
export type PATCH_DnsByZoneNameRecords_Response_422 = HTTPValidationError;

export type PATCH_DnsByZoneNameRrsets_Response = PATCH_DnsByZoneNameRrsets_Response_400 | PATCH_DnsByZoneNameRrsets_Response_422;

export type PATCH_DnsByZoneNameRrsets_Response_400 = Problem;
export type PATCH_DnsByZoneNameRrsets_Response_422 = HTTPValidationError;

export type PATCH_DnsByZoneNameVanitySet_Response = PATCH_DnsByZoneNameVanitySet_Response_200 | PATCH_DnsByZoneNameVanitySet_Response_400 | PATCH_DnsByZoneNameVanitySet_Response_422;

export type PATCH_DnsByZoneNameVanitySet_Response_200 = DnsZoneVanitySetUpdateRes;
export type PATCH_DnsByZoneNameVanitySet_Response_400 = Problem;
export type PATCH_DnsByZoneNameVanitySet_Response_422 = HTTPValidationError;

export type PATCH_DomainForwards_Response = PATCH_DomainForwards_Response_401 | PATCH_DomainForwards_Response_403 | PATCH_DomainForwards_Response_404 | PATCH_DomainForwards_Response_422;

export type PATCH_DomainForwards_Response_401 = Problem;
export type PATCH_DomainForwards_Response_403 = Problem;
export type PATCH_DomainForwards_Response_404 = Problem;
export type PATCH_DomainForwards_Response_422 = HTTPValidationError;

export type PATCH_DomainForwardsByHostnameDisable_Response = PATCH_DomainForwardsByHostnameDisable_Response_401 | PATCH_DomainForwardsByHostnameDisable_Response_403 | PATCH_DomainForwardsByHostnameDisable_Response_422;

export type PATCH_DomainForwardsByHostnameDisable_Response_401 = Problem;
export type PATCH_DomainForwardsByHostnameDisable_Response_403 = Problem;
export type PATCH_DomainForwardsByHostnameDisable_Response_422 = HTTPValidationError;

export type PATCH_DomainForwardsByHostnameEnable_Response = PATCH_DomainForwardsByHostnameEnable_Response_401 | PATCH_DomainForwardsByHostnameEnable_Response_403 | PATCH_DomainForwardsByHostnameEnable_Response_422;

export type PATCH_DomainForwardsByHostnameEnable_Response_401 = Problem;
export type PATCH_DomainForwardsByHostnameEnable_Response_403 = Problem;
export type PATCH_DomainForwardsByHostnameEnable_Response_422 = HTTPValidationError;

export type PATCH_DomainsByDomainReference_Response = PATCH_DomainsByDomainReference_Response_200 | PATCH_DomainsByDomainReference_Response_404 | PATCH_DomainsByDomainReference_Response_422;

export type PATCH_DomainsByDomainReference_Response_200 = Domain;
export type PATCH_DomainsByDomainReference_Response_404 = Problem;
export type PATCH_DomainsByDomainReference_Response_422 = HTTPValidationError;

export type PATCH_EmailForwardsByEmailForwardIdDisable_Response = PATCH_EmailForwardsByEmailForwardIdDisable_Response_401 | PATCH_EmailForwardsByEmailForwardIdDisable_Response_403 | PATCH_EmailForwardsByEmailForwardIdDisable_Response_404 | PATCH_EmailForwardsByEmailForwardIdDisable_Response_422;

export type PATCH_EmailForwardsByEmailForwardIdDisable_Response_401 = Problem;
export type PATCH_EmailForwardsByEmailForwardIdDisable_Response_403 = Problem;
export type PATCH_EmailForwardsByEmailForwardIdDisable_Response_404 = Problem;
export type PATCH_EmailForwardsByEmailForwardIdDisable_Response_422 = HTTPValidationError;

export type PATCH_EmailForwardsByEmailForwardIdEnable_Response = PATCH_EmailForwardsByEmailForwardIdEnable_Response_401 | PATCH_EmailForwardsByEmailForwardIdEnable_Response_403 | PATCH_EmailForwardsByEmailForwardIdEnable_Response_404 | PATCH_EmailForwardsByEmailForwardIdEnable_Response_422;

export type PATCH_EmailForwardsByEmailForwardIdEnable_Response_401 = Problem;
export type PATCH_EmailForwardsByEmailForwardIdEnable_Response_403 = Problem;
export type PATCH_EmailForwardsByEmailForwardIdEnable_Response_404 = Problem;
export type PATCH_EmailForwardsByEmailForwardIdEnable_Response_422 = HTTPValidationError;

export type PATCH_EventsByEventId_Response = PATCH_EventsByEventId_Response_401 | PATCH_EventsByEventId_Response_404 | PATCH_EventsByEventId_Response_422;

export type PATCH_EventsByEventId_Response_401 = Problem;
export type PATCH_EventsByEventId_Response_404 = Problem;
export type PATCH_EventsByEventId_Response_422 = HTTPValidationError;

export type PATCH_OrganizationsAttributes_Response = PATCH_OrganizationsAttributes_Response_200 | PATCH_OrganizationsAttributes_Response_401 | PATCH_OrganizationsAttributes_Response_403 | PATCH_OrganizationsAttributes_Response_422;

export type PATCH_OrganizationsAttributes_Response_200 = OrganizationAttribute2[];
export type PATCH_OrganizationsAttributes_Response_401 = Problem;
export type PATCH_OrganizationsAttributes_Response_403 = Problem;
export type PATCH_OrganizationsAttributes_Response_422 = HTTPValidationError;

export type PATCH_OrganizationsByOrganizationId_Response = PATCH_OrganizationsByOrganizationId_Response_200 | PATCH_OrganizationsByOrganizationId_Response_401 | PATCH_OrganizationsByOrganizationId_Response_403 | PATCH_OrganizationsByOrganizationId_Response_422;

export type PATCH_OrganizationsByOrganizationId_Response_200 = Organization;
export type PATCH_OrganizationsByOrganizationId_Response_401 = Problem;
export type PATCH_OrganizationsByOrganizationId_Response_403 = Problem;
export type PATCH_OrganizationsByOrganizationId_Response_422 = HTTPValidationError;

export type PATCH_OrganizationsByOrganizationIdAttributes_Response = PATCH_OrganizationsByOrganizationIdAttributes_Response_200 | PATCH_OrganizationsByOrganizationIdAttributes_Response_401 | PATCH_OrganizationsByOrganizationIdAttributes_Response_403 | PATCH_OrganizationsByOrganizationIdAttributes_Response_422;

export type PATCH_OrganizationsByOrganizationIdAttributes_Response_200 = OrganizationAttribute2[];
export type PATCH_OrganizationsByOrganizationIdAttributes_Response_401 = Problem;
export type PATCH_OrganizationsByOrganizationIdAttributes_Response_403 = Problem;
export type PATCH_OrganizationsByOrganizationIdAttributes_Response_422 = HTTPValidationError;

export type PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response = PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_200 | PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_401 | PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_403 | PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_422;

export type PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_200 = IpRestriction;
export type PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_401 = Problem;
export type PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_403 = Problem;
export type PATCH_OrganizationsIpRestrictionsByIpRestrictionId_Response_422 = HTTPValidationError;

export type PATCH_OrganizationsRolesByLabel_Response = PATCH_OrganizationsRolesByLabel_Response_200 | PATCH_OrganizationsRolesByLabel_Response_401 | PATCH_OrganizationsRolesByLabel_Response_403 | PATCH_OrganizationsRolesByLabel_Response_404 | PATCH_OrganizationsRolesByLabel_Response_409 | PATCH_OrganizationsRolesByLabel_Response_422;

export type PATCH_OrganizationsRolesByLabel_Response_200 = PublicRoleDefinition;
export type PATCH_OrganizationsRolesByLabel_Response_401 = Problem;
export type PATCH_OrganizationsRolesByLabel_Response_403 = Problem;
export type PATCH_OrganizationsRolesByLabel_Response_404 = Problem;
export type PATCH_OrganizationsRolesByLabel_Response_409 = Problem;
export type PATCH_OrganizationsRolesByLabel_Response_422 = HTTPValidationError;

export type PATCH_TagsByTagId_Response = PATCH_TagsByTagId_Response_200 | PATCH_TagsByTagId_Response_401 | PATCH_TagsByTagId_Response_404 | PATCH_TagsByTagId_Response_409 | PATCH_TagsByTagId_Response_422;

export type PATCH_TagsByTagId_Response_200 = Tag;
export type PATCH_TagsByTagId_Response_401 = Problem;
export type PATCH_TagsByTagId_Response_404 = Problem;
export type PATCH_TagsByTagId_Response_409 = Problem;
export type PATCH_TagsByTagId_Response_422 = HTTPValidationError;

export type PATCH_UsersByUserId_Response = PATCH_UsersByUserId_Response_200 | PATCH_UsersByUserId_Response_422;

export type PATCH_UsersByUserId_Response_200 = UserPublicWithAttributes;
export type PATCH_UsersByUserId_Response_422 = HTTPValidationError;

export type PATCH_VanityNameserverSetsBySetIdDefault_Response = PATCH_VanityNameserverSetsBySetIdDefault_Response_200 | PATCH_VanityNameserverSetsBySetIdDefault_Response_422;

export type PATCH_VanityNameserverSetsBySetIdDefault_Response_200 = SetVanityNameserverSetDefaultRes;
export type PATCH_VanityNameserverSetsBySetIdDefault_Response_422 = HTTPValidationError;

export type POST_AiConciergeConversations_Response = POST_AiConciergeConversations_Response_201 | POST_AiConciergeConversations_Response_401 | POST_AiConciergeConversations_Response_404 | POST_AiConciergeConversations_Response_422 | POST_AiConciergeConversations_Response_502;

export type POST_AiConciergeConversations_Response_201 = Conversation;
export type POST_AiConciergeConversations_Response_401 = Problem;
export type POST_AiConciergeConversations_Response_404 = Problem;
export type POST_AiConciergeConversations_Response_422 = HTTPValidationError;
export type POST_AiConciergeConversations_Response_502 = Problem;

export type POST_AiConciergeConversationsByConversationIdContexts_Response = POST_AiConciergeConversationsByConversationIdContexts_Response_401 | POST_AiConciergeConversationsByConversationIdContexts_Response_404 | POST_AiConciergeConversationsByConversationIdContexts_Response_422 | POST_AiConciergeConversationsByConversationIdContexts_Response_502;

export type POST_AiConciergeConversationsByConversationIdContexts_Response_401 = Problem;
export type POST_AiConciergeConversationsByConversationIdContexts_Response_404 = Problem;
export type POST_AiConciergeConversationsByConversationIdContexts_Response_422 = HTTPValidationError;
export type POST_AiConciergeConversationsByConversationIdContexts_Response_502 = Problem;

export type POST_AiConciergeConversationsByConversationIdMessages_Response = POST_AiConciergeConversationsByConversationIdMessages_Response_201 | POST_AiConciergeConversationsByConversationIdMessages_Response_401 | POST_AiConciergeConversationsByConversationIdMessages_Response_404 | POST_AiConciergeConversationsByConversationIdMessages_Response_422 | POST_AiConciergeConversationsByConversationIdMessages_Response_502;

export type POST_AiConciergeConversationsByConversationIdMessages_Response_201 = Message;
export type POST_AiConciergeConversationsByConversationIdMessages_Response_401 = Problem;
export type POST_AiConciergeConversationsByConversationIdMessages_Response_404 = Problem;
export type POST_AiConciergeConversationsByConversationIdMessages_Response_422 = HTTPValidationError;
export type POST_AiConciergeConversationsByConversationIdMessages_Response_502 = Problem;

export type POST_AiConciergeMemoryFacts_Response = POST_AiConciergeMemoryFacts_Response_201 | POST_AiConciergeMemoryFacts_Response_401 | POST_AiConciergeMemoryFacts_Response_404 | POST_AiConciergeMemoryFacts_Response_422 | POST_AiConciergeMemoryFacts_Response_502;

export type POST_AiConciergeMemoryFacts_Response_201 = MemoryFact;
export type POST_AiConciergeMemoryFacts_Response_401 = Problem;
export type POST_AiConciergeMemoryFacts_Response_404 = Problem;
export type POST_AiConciergeMemoryFacts_Response_422 = HTTPValidationError;
export type POST_AiConciergeMemoryFacts_Response_502 = Problem;

export type POST_AuthToken_Response = POST_AuthToken_Response_401;

export type POST_AuthToken_Response_401 = Problem;

export type POST_AvailabilityStream_Response = POST_AvailabilityStream_Response_401 | POST_AvailabilityStream_Response_422;

export type POST_AvailabilityStream_Response_401 = Problem;
export type POST_AvailabilityStream_Response_422 = HTTPValidationError;

export type POST_Contacts_Response = POST_Contacts_Response_201 | POST_Contacts_Response_422;

export type POST_Contacts_Response_201 = Contact;
export type POST_Contacts_Response_422 = HTTPValidationError;

export type POST_ContactsAttributeSets_Response = POST_ContactsAttributeSets_Response_201 | POST_ContactsAttributeSets_Response_409 | POST_ContactsAttributeSets_Response_422;

export type POST_ContactsAttributeSets_Response_201 = ContactAttributeSet;
export type POST_ContactsAttributeSets_Response_409 = Problem;
export type POST_ContactsAttributeSets_Response_422 = HTTPValidationError;

export type POST_ContactsByContactIdVerification_Response = POST_ContactsByContactIdVerification_Response_401 | POST_ContactsByContactIdVerification_Response_404 | POST_ContactsByContactIdVerification_Response_405 | POST_ContactsByContactIdVerification_Response_422;

export type POST_ContactsByContactIdVerification_Response_401 = Problem;
export type POST_ContactsByContactIdVerification_Response_404 = Problem;
export type POST_ContactsByContactIdVerification_Response_405 = Problem;
export type POST_ContactsByContactIdVerification_Response_422 = HTTPValidationError;

export type POST_ContactsByContactIdVerificationsAttest_Response = POST_ContactsByContactIdVerificationsAttest_Response_200 | POST_ContactsByContactIdVerificationsAttest_Response_400 | POST_ContactsByContactIdVerificationsAttest_Response_401 | POST_ContactsByContactIdVerificationsAttest_Response_404 | POST_ContactsByContactIdVerificationsAttest_Response_422 | POST_ContactsByContactIdVerificationsAttest_Response_502;

export type POST_ContactsByContactIdVerificationsAttest_Response_200 = ContactAttestRes;
export type POST_ContactsByContactIdVerificationsAttest_Response_400 = Problem;
export type POST_ContactsByContactIdVerificationsAttest_Response_401 = Problem;
export type POST_ContactsByContactIdVerificationsAttest_Response_404 = Problem;
export type POST_ContactsByContactIdVerificationsAttest_Response_422 = HTTPValidationError;
export type POST_ContactsByContactIdVerificationsAttest_Response_502 = Problem;

export type POST_Dns_Response = POST_Dns_Response_400 | POST_Dns_Response_422;

export type POST_Dns_Response_400 = Problem;
export type POST_Dns_Response_422 = HTTPValidationError;

export type POST_DnsByZoneNameDnssecDisable_Response = POST_DnsByZoneNameDnssecDisable_Response_200 | POST_DnsByZoneNameDnssecDisable_Response_400 | POST_DnsByZoneNameDnssecDisable_Response_422;

export type POST_DnsByZoneNameDnssecDisable_Response_200 = DnsChanges;
export type POST_DnsByZoneNameDnssecDisable_Response_400 = Problem;
export type POST_DnsByZoneNameDnssecDisable_Response_422 = HTTPValidationError;

export type POST_DnsByZoneNameDnssecEnable_Response = POST_DnsByZoneNameDnssecEnable_Response_200 | POST_DnsByZoneNameDnssecEnable_Response_400 | POST_DnsByZoneNameDnssecEnable_Response_422;

export type POST_DnsByZoneNameDnssecEnable_Response_200 = DnsChanges;
export type POST_DnsByZoneNameDnssecEnable_Response_400 = Problem;
export type POST_DnsByZoneNameDnssecEnable_Response_422 = HTTPValidationError;

export type POST_DomainForwards_Response = POST_DomainForwards_Response_201 | POST_DomainForwards_Response_401 | POST_DomainForwards_Response_403 | POST_DomainForwards_Response_404 | POST_DomainForwards_Response_409 | POST_DomainForwards_Response_422;

export type POST_DomainForwards_Response_201 = DomainForward;
export type POST_DomainForwards_Response_401 = Problem;
export type POST_DomainForwards_Response_403 = Problem;
export type POST_DomainForwards_Response_404 = Problem;
export type POST_DomainForwards_Response_409 = Problem;
export type POST_DomainForwards_Response_422 = HTTPValidationError;

export type POST_DomainForwardsByHostname_Response = POST_DomainForwardsByHostname_Response_201 | POST_DomainForwardsByHostname_Response_401 | POST_DomainForwardsByHostname_Response_403 | POST_DomainForwardsByHostname_Response_404 | POST_DomainForwardsByHostname_Response_409 | POST_DomainForwardsByHostname_Response_422;

export type POST_DomainForwardsByHostname_Response_201 = DomainForwardSet;
export type POST_DomainForwardsByHostname_Response_401 = Problem;
export type POST_DomainForwardsByHostname_Response_403 = Problem;
export type POST_DomainForwardsByHostname_Response_404 = Problem;
export type POST_DomainForwardsByHostname_Response_409 = Problem;
export type POST_DomainForwardsByHostname_Response_422 = HTTPValidationError;

export type POST_Domains_Response = POST_Domains_Response_201 | POST_Domains_Response_400 | POST_Domains_Response_404 | POST_Domains_Response_409 | POST_Domains_Response_422 | POST_Domains_Response_503;

export type POST_Domains_Response_201 = Domain;
export type POST_Domains_Response_400 = Problem;
export type POST_Domains_Response_404 = Problem;
export type POST_Domains_Response_409 = Problem;
export type POST_Domains_Response_422 = Problem;
export type POST_Domains_Response_503 = Problem;

export type POST_DomainsByDomainReferenceDnssecDisable_Response = POST_DomainsByDomainReferenceDnssecDisable_Response_404 | POST_DomainsByDomainReferenceDnssecDisable_Response_422;

export type POST_DomainsByDomainReferenceDnssecDisable_Response_404 = Problem;
export type POST_DomainsByDomainReferenceDnssecDisable_Response_422 = HTTPValidationError;

export type POST_DomainsByDomainReferenceDnssecEnable_Response = POST_DomainsByDomainReferenceDnssecEnable_Response_200 | POST_DomainsByDomainReferenceDnssecEnable_Response_404 | POST_DomainsByDomainReferenceDnssecEnable_Response_422;

export type POST_DomainsByDomainReferenceDnssecEnable_Response_200 = DomainDnssecData[];
export type POST_DomainsByDomainReferenceDnssecEnable_Response_404 = Problem;
export type POST_DomainsByDomainReferenceDnssecEnable_Response_422 = HTTPValidationError;

export type POST_DomainsByDomainReferenceRenew_Response = POST_DomainsByDomainReferenceRenew_Response_200 | POST_DomainsByDomainReferenceRenew_Response_422;

export type POST_DomainsByDomainReferenceRenew_Response_200 = DomainRenew;
export type POST_DomainsByDomainReferenceRenew_Response_422 = HTTPValidationError;

export type POST_DomainsByDomainReferenceRestore_Response = POST_DomainsByDomainReferenceRestore_Response_200 | POST_DomainsByDomainReferenceRestore_Response_422;

export type POST_DomainsByDomainReferenceRestore_Response_200 = DomainRestore;
export type POST_DomainsByDomainReferenceRestore_Response_422 = HTTPValidationError;

export type POST_DomainsClaimsNotices_Response = POST_DomainsClaimsNotices_Response_200 | POST_DomainsClaimsNotices_Response_404 | POST_DomainsClaimsNotices_Response_422 | POST_DomainsClaimsNotices_Response_503;

export type POST_DomainsClaimsNotices_Response_200 = ClaimsNotices;
export type POST_DomainsClaimsNotices_Response_404 = Problem;
export type POST_DomainsClaimsNotices_Response_422 = HTTPValidationError;
export type POST_DomainsClaimsNotices_Response_503 = Problem;

export type POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response = POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response_200 | POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response_404 | POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response_422;

export type POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response_200 = DomainWithdraw;
export type POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response_404 = Problem;
export type POST_DomainsTldSpecificAtByDomainReferenceWithdraw_Response_422 = HTTPValidationError;

export type POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response = POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_200 | POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_400 | POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_404 | POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_422;

export type POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_200 = RequestAuthcode;
export type POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_400 = Problem;
export type POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_404 = Problem;
export type POST_DomainsTldSpecificBeByDomainReferenceAuthCodeRequest_Response_422 = HTTPValidationError;

export type POST_DomainsTldSpecificDeByDomainReferenceTransit_Response = POST_DomainsTldSpecificDeByDomainReferenceTransit_Response_200 | POST_DomainsTldSpecificDeByDomainReferenceTransit_Response_404 | POST_DomainsTldSpecificDeByDomainReferenceTransit_Response_422;

export type POST_DomainsTldSpecificDeByDomainReferenceTransit_Response_200 = DomainTransit;
export type POST_DomainsTldSpecificDeByDomainReferenceTransit_Response_404 = Problem;
export type POST_DomainsTldSpecificDeByDomainReferenceTransit_Response_422 = HTTPValidationError;

export type POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response = POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_200 | POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_400 | POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_404 | POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_422;

export type POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_200 = RequestAuthcode2;
export type POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_400 = Problem;
export type POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_404 = Problem;
export type POST_DomainsTldSpecificEuByDomainReferenceAuthCodeRequest_Response_422 = HTTPValidationError;

export type POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response = POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_200 | POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_400 | POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_404 | POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_422;

export type POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_200 = RequestAuthcode3;
export type POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_400 = Problem;
export type POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_404 = Problem;
export type POST_DomainsTldSpecificLtByDomainReferenceAuthCodeRequest_Response_422 = HTTPValidationError;

export type POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response = POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_202 | POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_400 | POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_404 | POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_409 | POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_422;

export type POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_202 = NorIdDeclaration;
export type POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_400 = Problem;
export type POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_404 = Problem;
export type POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_409 = Problem;
export type POST_DomainsTldSpecificNoByDomainReferenceApplicantDeclaration_Response_422 = HTTPValidationError;

export type POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response = POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response_404 | POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response_409 | POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response_422;

export type POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response_404 = Problem;
export type POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response_409 = Problem;
export type POST_DomainsTldSpecificNoByDomainReferenceResendDeclarationEmail_Response_422 = HTTPValidationError;

export type POST_DomainsTransfer_Response = POST_DomainsTransfer_Response_201 | POST_DomainsTransfer_Response_400 | POST_DomainsTransfer_Response_403 | POST_DomainsTransfer_Response_404 | POST_DomainsTransfer_Response_409 | POST_DomainsTransfer_Response_422;

export type POST_DomainsTransfer_Response_201 = Domain;
export type POST_DomainsTransfer_Response_400 = Problem;
export type POST_DomainsTransfer_Response_403 = Problem;
export type POST_DomainsTransfer_Response_404 = Problem;
export type POST_DomainsTransfer_Response_409 = Problem;
export type POST_DomainsTransfer_Response_422 = Problem;

export type POST_EmailForwards_Response = POST_EmailForwards_Response_201 | POST_EmailForwards_Response_401 | POST_EmailForwards_Response_403 | POST_EmailForwards_Response_404 | POST_EmailForwards_Response_409 | POST_EmailForwards_Response_422;

export type POST_EmailForwards_Response_201 = EmailForward;
export type POST_EmailForwards_Response_401 = Problem;
export type POST_EmailForwards_Response_403 = Problem;
export type POST_EmailForwards_Response_404 = Problem;
export type POST_EmailForwards_Response_409 = Problem;
export type POST_EmailForwards_Response_422 = HTTPValidationError;

export type POST_EmailForwardsByEmailForwardIdAliases_Response = POST_EmailForwardsByEmailForwardIdAliases_Response_201 | POST_EmailForwardsByEmailForwardIdAliases_Response_401 | POST_EmailForwardsByEmailForwardIdAliases_Response_403 | POST_EmailForwardsByEmailForwardIdAliases_Response_404 | POST_EmailForwardsByEmailForwardIdAliases_Response_409 | POST_EmailForwardsByEmailForwardIdAliases_Response_422;

export type POST_EmailForwardsByEmailForwardIdAliases_Response_201 = EmailForwardAlias;
export type POST_EmailForwardsByEmailForwardIdAliases_Response_401 = Problem;
export type POST_EmailForwardsByEmailForwardIdAliases_Response_403 = Problem;
export type POST_EmailForwardsByEmailForwardIdAliases_Response_404 = Problem;
export type POST_EmailForwardsByEmailForwardIdAliases_Response_409 = Problem;
export type POST_EmailForwardsByEmailForwardIdAliases_Response_422 = HTTPValidationError;

export type POST_Hosts_Response = POST_Hosts_Response_201 | POST_Hosts_Response_401 | POST_Hosts_Response_403 | POST_Hosts_Response_404 | POST_Hosts_Response_409 | POST_Hosts_Response_422;

export type POST_Hosts_Response_201 = Host;
export type POST_Hosts_Response_401 = Problem;
export type POST_Hosts_Response_403 = Problem;
export type POST_Hosts_Response_404 = Problem;
export type POST_Hosts_Response_409 = Problem;
export type POST_Hosts_Response_422 = Problem;

export type POST_JobByJobIdPause_Response = POST_JobByJobIdPause_Response_404 | POST_JobByJobIdPause_Response_422;

export type POST_JobByJobIdPause_Response_404 = Problem;
export type POST_JobByJobIdPause_Response_422 = HTTPValidationError;

export type POST_JobByJobIdResume_Response = POST_JobByJobIdResume_Response_200 | POST_JobByJobIdResume_Response_404 | POST_JobByJobIdResume_Response_422;

export type POST_JobByJobIdResume_Response_200 = Job;
export type POST_JobByJobIdResume_Response_404 = Problem;
export type POST_JobByJobIdResume_Response_422 = HTTPValidationError;

export type POST_JobByJobIdRetry_Response = POST_JobByJobIdRetry_Response_200 | POST_JobByJobIdRetry_Response_404 | POST_JobByJobIdRetry_Response_409 | POST_JobByJobIdRetry_Response_422;

export type POST_JobByJobIdRetry_Response_200 = Job;
export type POST_JobByJobIdRetry_Response_404 = Problem;
export type POST_JobByJobIdRetry_Response_409 = Problem;
export type POST_JobByJobIdRetry_Response_422 = HTTPValidationError;

export type POST_Jobs_Response = POST_Jobs_Response_201 | POST_Jobs_Response_400 | POST_Jobs_Response_422 | POST_Jobs_Response_503;

export type POST_Jobs_Response_201 = CreateJobBatch;
export type POST_Jobs_Response_400 = Problem;
export type POST_Jobs_Response_422 = HTTPValidationError;
export type POST_Jobs_Response_503 = Problem;

export type POST_JobsByBatchIdPause_Response = POST_JobsByBatchIdPause_Response_404 | POST_JobsByBatchIdPause_Response_422;

export type POST_JobsByBatchIdPause_Response_404 = Problem;
export type POST_JobsByBatchIdPause_Response_422 = HTTPValidationError;

export type POST_JobsByBatchIdResume_Response = POST_JobsByBatchIdResume_Response_404 | POST_JobsByBatchIdResume_Response_422;

export type POST_JobsByBatchIdResume_Response_404 = Problem;
export type POST_JobsByBatchIdResume_Response_422 = HTTPValidationError;

export type POST_JobsByBatchIdRetry_Response = POST_JobsByBatchIdRetry_Response_200 | POST_JobsByBatchIdRetry_Response_404 | POST_JobsByBatchIdRetry_Response_422;

export type POST_JobsByBatchIdRetry_Response_200 = JobBatchRetry;
export type POST_JobsByBatchIdRetry_Response_404 = Problem;
export type POST_JobsByBatchIdRetry_Response_422 = HTTPValidationError;

export type POST_Organizations_Response = POST_Organizations_Response_200 | POST_Organizations_Response_401 | POST_Organizations_Response_403 | POST_Organizations_Response_422;

export type POST_Organizations_Response_200 = Organization;
export type POST_Organizations_Response_401 = Problem;
export type POST_Organizations_Response_403 = Problem;
export type POST_Organizations_Response_422 = Problem;

export type POST_OrganizationsIpRestrictions_Response = POST_OrganizationsIpRestrictions_Response_200 | POST_OrganizationsIpRestrictions_Response_401 | POST_OrganizationsIpRestrictions_Response_403 | POST_OrganizationsIpRestrictions_Response_422;

export type POST_OrganizationsIpRestrictions_Response_200 = IpRestriction;
export type POST_OrganizationsIpRestrictions_Response_401 = Problem;
export type POST_OrganizationsIpRestrictions_Response_403 = Problem;
export type POST_OrganizationsIpRestrictions_Response_422 = HTTPValidationError;

export type POST_OrganizationsRoles_Response = POST_OrganizationsRoles_Response_201 | POST_OrganizationsRoles_Response_401 | POST_OrganizationsRoles_Response_403 | POST_OrganizationsRoles_Response_409 | POST_OrganizationsRoles_Response_422;

export type POST_OrganizationsRoles_Response_201 = PublicRoleDefinition;
export type POST_OrganizationsRoles_Response_401 = Problem;
export type POST_OrganizationsRoles_Response_403 = Problem;
export type POST_OrganizationsRoles_Response_409 = Problem;
export type POST_OrganizationsRoles_Response_422 = HTTPValidationError;

export type POST_ParkingSignup_Response = POST_ParkingSignup_Response_200 | POST_ParkingSignup_Response_401 | POST_ParkingSignup_Response_403 | POST_ParkingSignup_Response_422;

export type POST_ParkingSignup_Response_200 = ParkingSignup;
export type POST_ParkingSignup_Response_401 = Problem;
export type POST_ParkingSignup_Response_403 = Problem;
export type POST_ParkingSignup_Response_422 = HTTPValidationError;

export type POST_Reports_Response = POST_Reports_Response_422;

export type POST_Reports_Response_422 = HTTPValidationError;

export type POST_Tags_Response = POST_Tags_Response_201 | POST_Tags_Response_401 | POST_Tags_Response_409 | POST_Tags_Response_422;

export type POST_Tags_Response_201 = Tag;
export type POST_Tags_Response_401 = Problem;
export type POST_Tags_Response_409 = Problem;
export type POST_Tags_Response_422 = HTTPValidationError;

export type POST_TagsByTagIdObjects_Response = POST_TagsByTagIdObjects_Response_200 | POST_TagsByTagIdObjects_Response_401 | POST_TagsByTagIdObjects_Response_404 | POST_TagsByTagIdObjects_Response_422;

export type POST_TagsByTagIdObjects_Response_200 = ObjectTagChanges2;
export type POST_TagsByTagIdObjects_Response_401 = Problem;
export type POST_TagsByTagIdObjects_Response_404 = Problem;
export type POST_TagsByTagIdObjects_Response_422 = HTTPValidationError;

export type POST_TagsObjects_Response = POST_TagsObjects_Response_200 | POST_TagsObjects_Response_400 | POST_TagsObjects_Response_401 | POST_TagsObjects_Response_404 | POST_TagsObjects_Response_422;

export type POST_TagsObjects_Response_200 = ObjectTagChanges2;
export type POST_TagsObjects_Response_400 = Problem;
export type POST_TagsObjects_Response_401 = Problem;
export type POST_TagsObjects_Response_404 = Problem;
export type POST_TagsObjects_Response_422 = HTTPValidationError;

export type POST_Users_Response = POST_Users_Response_200 | POST_Users_Response_422;

export type POST_Users_Response_200 = UserPublic;
export type POST_Users_Response_422 = HTTPValidationError;

export type POST_VanityNameserverSets_Response = POST_VanityNameserverSets_Response_202 | POST_VanityNameserverSets_Response_422;

export type POST_VanityNameserverSets_Response_202 = VanityNameserverSetSummaryDTO;
export type POST_VanityNameserverSets_Response_422 = HTTPValidationError;

export type POST_VanityNameserverSetsBySetIdRestore_Response = POST_VanityNameserverSetsBySetIdRestore_Response_200 | POST_VanityNameserverSetsBySetIdRestore_Response_422;

export type POST_VanityNameserverSetsBySetIdRestore_Response_200 = VanityNameserverSetSummaryDTO;
export type POST_VanityNameserverSetsBySetIdRestore_Response_422 = HTTPValidationError;

export type POST_VanityNameserverSetsBySetIdRetry_Response = POST_VanityNameserverSetsBySetIdRetry_Response_202 | POST_VanityNameserverSetsBySetIdRetry_Response_422;

export type POST_VanityNameserverSetsBySetIdRetry_Response_202 = VanityNameserverSetSummaryDTO;
export type POST_VanityNameserverSetsBySetIdRetry_Response_422 = HTTPValidationError;

export type POST_VanityNameserverSetsCheck_Response = POST_VanityNameserverSetsCheck_Response_200 | POST_VanityNameserverSetsCheck_Response_422;

export type POST_VanityNameserverSetsCheck_Response_200 = VanityNsCheckRes;
export type POST_VanityNameserverSetsCheck_Response_422 = HTTPValidationError;

export type PUT_ContactsByContactIdVerification_Response = PUT_ContactsByContactIdVerification_Response_400 | PUT_ContactsByContactIdVerification_Response_401 | PUT_ContactsByContactIdVerification_Response_403 | PUT_ContactsByContactIdVerification_Response_404 | PUT_ContactsByContactIdVerification_Response_422;

export type PUT_ContactsByContactIdVerification_Response_400 = Problem;
export type PUT_ContactsByContactIdVerification_Response_401 = Problem;
export type PUT_ContactsByContactIdVerification_Response_403 = Problem;
export type PUT_ContactsByContactIdVerification_Response_404 = Problem;
export type PUT_ContactsByContactIdVerification_Response_422 = HTTPValidationError;

export type PUT_ContactsVerification_Response = PUT_ContactsVerification_Response_400 | PUT_ContactsVerification_Response_401 | PUT_ContactsVerification_Response_404 | PUT_ContactsVerification_Response_422;

export type PUT_ContactsVerification_Response_400 = Problem;
export type PUT_ContactsVerification_Response_401 = Problem;
export type PUT_ContactsVerification_Response_404 = Problem;
export type PUT_ContactsVerification_Response_422 = HTTPValidationError;

export type PUT_DnsByZoneNameRrsets_Response = PUT_DnsByZoneNameRrsets_Response_400 | PUT_DnsByZoneNameRrsets_Response_422;

export type PUT_DnsByZoneNameRrsets_Response_400 = Problem;
export type PUT_DnsByZoneNameRrsets_Response_422 = HTTPValidationError;

export type PUT_DomainForwardsByHostnameByProtocol_Response = PUT_DomainForwardsByHostnameByProtocol_Response_200 | PUT_DomainForwardsByHostnameByProtocol_Response_401 | PUT_DomainForwardsByHostnameByProtocol_Response_403 | PUT_DomainForwardsByHostnameByProtocol_Response_404 | PUT_DomainForwardsByHostnameByProtocol_Response_422;

export type PUT_DomainForwardsByHostnameByProtocol_Response_200 = DomainForwardSet;
export type PUT_DomainForwardsByHostnameByProtocol_Response_401 = Problem;
export type PUT_DomainForwardsByHostnameByProtocol_Response_403 = Problem;
export type PUT_DomainForwardsByHostnameByProtocol_Response_404 = Problem;
export type PUT_DomainForwardsByHostnameByProtocol_Response_422 = HTTPValidationError;

export type PUT_DomainsByDomainReferenceDnssec_Response = PUT_DomainsByDomainReferenceDnssec_Response_200 | PUT_DomainsByDomainReferenceDnssec_Response_404 | PUT_DomainsByDomainReferenceDnssec_Response_422;

export type PUT_DomainsByDomainReferenceDnssec_Response_200 = DomainDnssecData[];
export type PUT_DomainsByDomainReferenceDnssec_Response_404 = Problem;
export type PUT_DomainsByDomainReferenceDnssec_Response_422 = Problem;

export type PUT_DomainsTldSpecificNoApplicantDeclaration_Response = PUT_DomainsTldSpecificNoApplicantDeclaration_Response_400 | PUT_DomainsTldSpecificNoApplicantDeclaration_Response_404 | PUT_DomainsTldSpecificNoApplicantDeclaration_Response_409 | PUT_DomainsTldSpecificNoApplicantDeclaration_Response_422;

export type PUT_DomainsTldSpecificNoApplicantDeclaration_Response_400 = Problem;
export type PUT_DomainsTldSpecificNoApplicantDeclaration_Response_404 = Problem;
export type PUT_DomainsTldSpecificNoApplicantDeclaration_Response_409 = Problem;
export type PUT_DomainsTldSpecificNoApplicantDeclaration_Response_422 = HTTPValidationError;

export type PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response = PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_200 | PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_401 | PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_403 | PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_404 | PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_422;

export type PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_200 = EmailForwardAlias;
export type PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_401 = Problem;
export type PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_403 = Problem;
export type PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_404 = Problem;
export type PUT_EmailForwardsByEmailForwardIdAliasesByAliasId_Response_422 = HTTPValidationError;

export type PUT_HostsByHostReference_Response = PUT_HostsByHostReference_Response_200 | PUT_HostsByHostReference_Response_401 | PUT_HostsByHostReference_Response_403 | PUT_HostsByHostReference_Response_404 | PUT_HostsByHostReference_Response_422;

export type PUT_HostsByHostReference_Response_200 = Host;
export type PUT_HostsByHostReference_Response_401 = Problem;
export type PUT_HostsByHostReference_Response_403 = Problem;
export type PUT_HostsByHostReference_Response_404 = Problem;
export type PUT_HostsByHostReference_Response_422 = HTTPValidationError;

export type PUT_UsersByUserIdRole_Response = PUT_UsersByUserIdRole_Response_200 | PUT_UsersByUserIdRole_Response_403 | PUT_UsersByUserIdRole_Response_404 | PUT_UsersByUserIdRole_Response_422;

export type PUT_UsersByUserIdRole_Response_200 = PublicRoleAssignment;
export type PUT_UsersByUserIdRole_Response_403 = Problem;
export type PUT_UsersByUserIdRole_Response_404 = Problem;
export type PUT_UsersByUserIdRole_Response_422 = HTTPValidationError;
