#!/usr/bin/env python3
"""Mirror the OpusDNS MCP server docs into the Scalar site.

Copies ``docs/scalar`` from a checkout of OpusDNS/opusdns-mcp into
``scalar/content/mcp-server`` and registers the pages in
``scalar/scalar.config.json``.

The Markdown is **copied, not generated**: opusdns-mcp renders it with
``make docs`` from its committed tools/list snapshot and its CI fails when the
committed output drifts. So there is exactly one renderer, and this repo needs no
Go toolchain.

Run from the api-spec root:

    python scripts/sync_mcp_docs.py --source ../opusdns-mcp/docs/scalar
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from mcp_docs import scalar_config  # noqa: E402

DEFAULT_SOURCE = REPO_ROOT.parent / "opusdns-mcp" / "docs" / "scalar"
DEFAULT_CONTENT = REPO_ROOT / "scalar" / "content" / "mcp-server"
DEFAULT_CONFIG = REPO_ROOT / "scalar" / "scalar.config.json"

# Files the manifest never declares and that must not be published: the partials
# are merged into generated pages upstream, and the README documents the source
# tree for engineers, not for readers of the site.
NEVER_PUBLISH = {"README.md", "nav.json"}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help="docs/scalar in an opusdns-mcp checkout (default: %(default)s)",
    )
    parser.add_argument(
        "--content",
        type=Path,
        default=DEFAULT_CONTENT,
        help="target content directory (default: %(default)s)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="path to scalar.config.json (default: %(default)s)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="report what would change without writing anything",
    )
    return parser.parse_args(argv)


def load_manifest(source: Path) -> dict:
    path = source / "nav.json"
    if not path.is_file():
        raise SystemExit(
            f"{path} is missing. It is generated by `make docs` in opusdns-mcp; "
            "a checkout without it is incomplete."
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path} is not valid JSON: {exc}") from exc


def declared_files(manifest: dict) -> list[str]:
    out: list[str] = []

    def walk(entries: list[dict]) -> None:
        for entry in entries:
            if entry.get("file"):
                out.append(entry["file"])
            walk(entry.get("children") or [])

    walk(manifest.get("children") or [])
    return out


def copy_pages(source: Path, content: Path, files: list[str], dry_run: bool) -> list[str]:
    """Copy each declared page, writing only what changed."""
    changed: list[str] = []
    for rel in files:
        src = source / rel
        if not src.is_file():
            raise SystemExit(
                f"nav.json declares {rel}, which is missing from {source}. "
                "Run `make docs` in opusdns-mcp and commit the result."
            )
        dst = content / rel
        body = src.read_bytes()
        if dst.is_file() and dst.read_bytes() == body:
            continue
        changed.append(rel)
        if dry_run:
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
    return changed


def prune(content: Path, files: list[str], dry_run: bool) -> list[str]:
    """Delete published pages the manifest no longer declares."""
    keep = {(content / rel).resolve() for rel in files}
    removed: list[str] = []
    if not content.is_dir():
        return removed
    for path in sorted(content.rglob("*.md")):
        if path.resolve() in keep:
            continue
        removed.append(str(path.relative_to(content)))
        if not dry_run:
            path.unlink()
    # Clean up any directory the pruning emptied.
    if not dry_run:
        for path in sorted(content.rglob("*"), reverse=True):
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    return removed


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if not args.source.is_dir():
        raise SystemExit(f"{args.source} is not a directory")

    manifest = load_manifest(args.source)
    files = declared_files(manifest)
    if not files:
        # The same guard as in scalar_config, one step earlier: never let a bad
        # checkout empty the published section.
        raise SystemExit("nav.json declares no pages; refusing to empty the published section")
    for rel in files:
        if Path(rel).name in NEVER_PUBLISH:
            raise SystemExit(f"nav.json declares {rel}, which is not publishable")

    copied = copy_pages(args.source, args.content, files, args.dry_run)
    removed = prune(args.content, files, args.dry_run)

    config_changed = False
    if args.dry_run:
        # Validate the manifest and the nav rewrite without touching the file.
        # scalar_root is deliberately omitted: nothing was copied, so the
        # filepath-exists check would report every declared page as missing.
        # copy_pages has already verified each one exists in the source.
        scratch = args.config.parent / ".scalar.config.dry-run.json"
        try:
            shutil.copyfile(args.config, scratch)
            config_changed = scalar_config.update_config(scratch, manifest=manifest)
        finally:
            scratch.unlink(missing_ok=True)
    else:
        config_changed = scalar_config.update_config(
            args.config, manifest=manifest, scalar_root=args.config.parent
        )

    prefix = "would " if args.dry_run else ""
    for rel in copied:
        print(f"{prefix}update {args.content.name}/{rel}")
    for rel in removed:
        print(f"{prefix}remove {args.content.name}/{rel}")
    print(f"{args.config.name}: {prefix}{'update' if config_changed else 'unchanged'}")
    if not copied and not removed and not config_changed:
        print("already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
